// <autogenerated>
//   This file was generated by T4 code generator GenerateRamlClientProxies.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Dddml.Wms.Domain;

using Dddml.Wms.Specialization;
using Dddml.Wms.HttpServices.ClientProxies.Raml;
using Dddml.Wms.HttpServices.ClientProxies.Raml.Models;
using System.Text;
using System.ComponentModel;


namespace Dddml.Wms.HttpServices.ClientProxies
{

    public partial class AttributeApplicationServiceProxy : IAttributeApplicationService
    {


        private DddmlWmsRamlClient _ramlClient;

        public AttributeApplicationServiceProxy(string endpointUrl)
        {
            _ramlClient = new DddmlWmsRamlClient(endpointUrl);
        }

        public AttributeApplicationServiceProxy(HttpClient httpClient)
        {
            _ramlClient = new DddmlWmsRamlClient(httpClient);
        }

        public void When(CreateAttributeDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as ICreateAttribute).AttributeId);
            var uriParameters = new AttributeUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributePutRequest(uriParameters, (CreateAttributeDto)c);
                
            var resp = _ramlClient.Attribute.Put(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(MergePatchAttributeDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IMergePatchAttribute).AttributeId);
            var uriParameters = new AttributeUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributePatchRequest(uriParameters, (MergePatchAttributeDto)c);
            var resp = _ramlClient.Attribute.Patch(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(DeleteAttributeDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IDeleteAttribute).AttributeId);
            var uriParameters = new AttributeUriParameters();
            uriParameters.Id = idObj;

            var q = new AttributeDeleteQuery();
            q.CommandId = c.CommandId;
                
            var req = new AttributeDeleteRequest(uriParameters);
            req.Query = q;

            var resp = _ramlClient.Attribute.Delete(req).GetAwaiter().GetResult();;
            //};
            //act();
        }
		
        void IAttributeApplicationService.When(ICreateAttribute c)
        {
            this.When((CreateAttributeDto)c);
        }

        void IAttributeApplicationService.When(IMergePatchAttribute c)
        {
            this.When((MergePatchAttributeDto)c);
        }

        void IAttributeApplicationService.When(IDeleteAttribute c)
        {
            this.When((DeleteAttributeDto)c);
        }

        public IAttributeState Get(string attributeId)
        {
            IAttributeState state = null;
            //Action act = async () =>
            //{
            var idObj = (attributeId);
            var uriParameters = new AttributeUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeGetRequest(uriParameters);

            var resp = _ramlClient.Attribute.Get(req).GetAwaiter().GetResult();
            state = resp.Content;
            //};
            //act();
            return state;
        }

        public IEnumerable<IAttributeState> GetAll(int firstResult, int maxResults)
        {
            return Get(null, null, firstResult, maxResults);
        }

        public IEnumerable<IAttributeState> Get(IDictionary<string, object> filter, IList<string> orders = null, int firstResult = 0, int maxResults = int.MaxValue)
        {
            return Get(filter, orders, firstResult, maxResults, null);
        }

        public IEnumerable<IAttributeState> Get(IDictionary<string, object> filter, IList<string> orders = null, int firstResult = 0, int maxResults = int.MaxValue, IList<string> fields = null)
        {
            IEnumerable<IAttributeState> states = null;
            //Action act = async () =>
            //{
			var q = new AttributesGetQuery();
			q.FirstResult = firstResult;
			q.MaxResults = maxResults;
            q.Sort = GetOrdersQueryValueString(orders);
            q.Fields = GetReturnedFieldsQueryValueString(fields);
            q.FilterTag = GetFilterTagQueryValueString(filter);
            var req = new AttributesGetRequest();
            req.Query = q;
            var resp = _ramlClient.Attributes.Get(req).GetAwaiter().GetResult();;
            states = resp.Content;
            //};
            //act();
            return states;
        }


        public virtual void Execute(object command)
        {
            ((dynamic)this).When((dynamic)command);
        }



        protected virtual string GetFilterTagQueryValueString(IDictionary<string, object> filter)
        {
            if (filter == null) { return null; }
            StringBuilder sb = new StringBuilder();
            sb.Append(DateTime.Now.Ticks);
            foreach (var p in filter)
            {
                var k = p.Key;
                var v = p.Value;
                sb.Append("&");
                sb.Append(k);
                sb.Append("=");
                if (v != null)
                {
                    var converter = TypeDescriptor.GetConverter(v.GetType());
                    string valStr = converter.ConvertToString(v);
                    sb.Append(WebUtility.UrlEncode(valStr));
                }

            }
            return sb.ToString();
        }

        protected virtual string GetReturnedFieldsQueryValueString(IList<string> fields)
        {
            if (fields == null) { return null; }
            StringBuilder sb = new StringBuilder();
            foreach (var f in fields)
            {
                sb.Append(WebUtility.UrlEncode(f));
                sb.Append(QueryFieldValueSeparator);
            }
            return sb.ToString();
        }

        protected virtual string GetOrdersQueryValueString(IList<string> orders)
        {
            if (orders == null) { return null; }
            StringBuilder sb = new StringBuilder();
            foreach (var ord in orders)
            {
                sb.Append(WebUtility.UrlEncode(ord));
                sb.Append(",");
            }
            return sb.ToString();
        }


        protected virtual string QueryFieldValueSeparator
        {
            get { return ","; }
        }

        protected virtual string QueryOrderSeparator
        {
            get { return ","; }
        }

    }


    public partial class AttributeApplicationServiceProxyFactory : IAttributeApplicationServiceFactory
    {

        private string _endpointUrl;

        public AttributeApplicationServiceProxyFactory(string endpointUrl)
        {
            this._endpointUrl = endpointUrl;
        }

        public IAttributeApplicationService AttributeApplicationService
        {
            get
            {
                return new AttributeApplicationServiceProxy(_endpointUrl);
            }
        }

        public ICreateAttribute NewCreateAttribute()
        {
            return new CreateAttributeDto();
        }

        public IMergePatchAttribute NewMergePatchAttribute()
        {
            return new MergePatchAttributeDto();
        }

        public IDeleteAttribute NewDeleteAttribute()
        {
            return new DeleteAttributeDto();
        }
    }


}

