// <autogenerated>
//   This file was generated by T4 code generator GenerateRamlClientProxies.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Dddml.Wms.Domain;

using Dddml.Wms.Specialization;
using Dddml.Wms.HttpServices.ClientProxies.Raml;
using Dddml.Wms.HttpServices.ClientProxies.Raml.Models;

namespace Dddml.Wms.HttpServices.ClientProxies
{

    public partial class AttributeSetApplicationServiceProxy : IAttributeSetApplicationService
    {


        private DddmlWmsRamlClient _ramlClient;

        public AttributeSetApplicationServiceProxy(string endpointUrl)
        {
            _ramlClient = new DddmlWmsRamlClient(endpointUrl);
        }

        public AttributeSetApplicationServiceProxy(HttpClient httpClient)
        {
            _ramlClient = new DddmlWmsRamlClient(httpClient);
        }

        public void When(CreateAttributeSetDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as ICreateAttributeSet).AttributeSetId);
            var uriParameters = new AttributeSetUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetPutRequest(uriParameters, (CreateAttributeSetDto)c);
                
            var resp = _ramlClient.AttributeSet.Put(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(MergePatchAttributeSetDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IMergePatchAttributeSet).AttributeSetId);
            var uriParameters = new AttributeSetUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetPatchRequest(uriParameters, (MergePatchAttributeSetDto)c);
            var resp = _ramlClient.AttributeSet.Patch(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(DeleteAttributeSetDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IDeleteAttributeSet).AttributeSetId);
            var uriParameters = new AttributeSetUriParameters();
            uriParameters.Id = idObj;

            var q = new AttributeSetDeleteQuery();
            q.CommandId = c.CommandId;
                
            var req = new AttributeSetDeleteRequest(uriParameters);
            req.Query = q;

            var resp = _ramlClient.AttributeSet.Delete(req).GetAwaiter().GetResult();;
            //};
            //act();
        }
		
        void IAttributeSetApplicationService.When(ICreateAttributeSet c)
        {
            this.When((CreateAttributeSetDto)c);
        }

        void IAttributeSetApplicationService.When(IMergePatchAttributeSet c)
        {
            this.When((MergePatchAttributeSetDto)c);
        }

        void IAttributeSetApplicationService.When(IDeleteAttributeSet c)
        {
            this.When((DeleteAttributeSetDto)c);
        }

        public IAttributeSetState Get(string attributeSetId)
        {
            IAttributeSetState state = null;
            //Action act = async () =>
            //{
            var idObj = (attributeSetId);
            var uriParameters = new AttributeSetUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetGetRequest(uriParameters);

            var resp = _ramlClient.AttributeSet.Get(req).GetAwaiter().GetResult();
            state = resp.Content;
            //};
            //act();
            return state;
        }

        public IEnumerable<IAttributeSetState> GetAll(int firstResult, int maxResults)
        {
            IEnumerable<IAttributeSetState> states = null;
            //Action act = async () =>
            //{
			var q = new AttributeSetsGetQuery();
			q.FirstResult = firstResult;
			q.MaxResults = maxResults;
            var req = new AttributeSetsGetRequest();
            req.Query = q;
            var resp = _ramlClient.AttributeSets.Get(req).GetAwaiter().GetResult();;
            states = resp.Content;
            //};
            //act();
            return states;
        }

        public virtual void Execute(object command)
        {
            ((dynamic)this).When((dynamic)command);
        }



    }


    public partial class AttributeSetApplicationServiceProxyFactory : IAttributeSetApplicationServiceFactory
    {

        private string _endpointUrl;

        public AttributeSetApplicationServiceProxyFactory(string endpointUrl)
        {
            this._endpointUrl = endpointUrl;
        }

        public IAttributeSetApplicationService AttributeSetApplicationService
        {
            get
            {
                return new AttributeSetApplicationServiceProxy(_endpointUrl);
            }
        }

        public ICreateAttributeSet NewCreateAttributeSet()
        {
            return new CreateAttributeSetDto();
        }

        public IMergePatchAttributeSet NewMergePatchAttributeSet()
        {
            return new MergePatchAttributeSetDto();
        }

        public IDeleteAttributeSet NewDeleteAttributeSet()
        {
            return new DeleteAttributeSetDto();
        }
    }


}

