// <autogenerated>
//   This file was generated by T4 code generator GenerateRamlClientProxies.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Dddml.Wms.Domain;

using Dddml.Wms.Specialization;
using Dddml.Wms.HttpServices.ClientProxies.Raml;
using Dddml.Wms.HttpServices.ClientProxies.Raml.Models;

namespace Dddml.Wms.HttpServices.ClientProxies
{

    public partial class AttributeSetInstanceExtensionFieldGroupApplicationServiceProxy : IAttributeSetInstanceExtensionFieldGroupApplicationService
    {


        private DddmlWmsRamlClient _ramlClient;

        public AttributeSetInstanceExtensionFieldGroupApplicationServiceProxy(string endpointUrl)
        {
            _ramlClient = new DddmlWmsRamlClient(endpointUrl);
        }

        public AttributeSetInstanceExtensionFieldGroupApplicationServiceProxy(HttpClient httpClient)
        {
            _ramlClient = new DddmlWmsRamlClient(httpClient);
        }

        public void When(CreateAttributeSetInstanceExtensionFieldGroupDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as ICreateAttributeSetInstanceExtensionFieldGroup).Id);
            var uriParameters = new AttributeSetInstanceExtensionFieldGroupUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetInstanceExtensionFieldGroupPutRequest(uriParameters, (CreateAttributeSetInstanceExtensionFieldGroupDto)c);
                
            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroup.Put(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(MergePatchAttributeSetInstanceExtensionFieldGroupDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IMergePatchAttributeSetInstanceExtensionFieldGroup).Id);
            var uriParameters = new AttributeSetInstanceExtensionFieldGroupUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetInstanceExtensionFieldGroupPatchRequest(uriParameters, (MergePatchAttributeSetInstanceExtensionFieldGroupDto)c);
            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroup.Patch(req).GetAwaiter().GetResult();;
            //};
            //act();
        }

        public void When(DeleteAttributeSetInstanceExtensionFieldGroupDto c)
        {
            //Action act = async () =>
            //{
            var idObj = ((c as IDeleteAttributeSetInstanceExtensionFieldGroup).Id);
            var uriParameters = new AttributeSetInstanceExtensionFieldGroupUriParameters();
            uriParameters.Id = idObj;

            var q = new AttributeSetInstanceExtensionFieldGroupDeleteQuery();
            q.CommandId = c.CommandId;
                
            var req = new AttributeSetInstanceExtensionFieldGroupDeleteRequest(uriParameters);
            req.Query = q;

            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroup.Delete(req).GetAwaiter().GetResult();;
            //};
            //act();
        }
		
        void IAttributeSetInstanceExtensionFieldGroupApplicationService.When(ICreateAttributeSetInstanceExtensionFieldGroup c)
        {
            this.When((CreateAttributeSetInstanceExtensionFieldGroupDto)c);
        }

        void IAttributeSetInstanceExtensionFieldGroupApplicationService.When(IMergePatchAttributeSetInstanceExtensionFieldGroup c)
        {
            this.When((MergePatchAttributeSetInstanceExtensionFieldGroupDto)c);
        }

        void IAttributeSetInstanceExtensionFieldGroupApplicationService.When(IDeleteAttributeSetInstanceExtensionFieldGroup c)
        {
            this.When((DeleteAttributeSetInstanceExtensionFieldGroupDto)c);
        }

        public IAttributeSetInstanceExtensionFieldGroupState Get(string id)
        {
            IAttributeSetInstanceExtensionFieldGroupState state = null;
            //Action act = async () =>
            //{
            var idObj = (id);
            var uriParameters = new AttributeSetInstanceExtensionFieldGroupUriParameters();
            uriParameters.Id = idObj;

            var req = new AttributeSetInstanceExtensionFieldGroupGetRequest(uriParameters);

            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroup.Get(req).GetAwaiter().GetResult();
            state = resp.Content;
            //};
            //act();
            return state;
        }

        public IEnumerable<IAttributeSetInstanceExtensionFieldGroupState> GetAll(int firstResult, int maxResults)
        {
            IEnumerable<IAttributeSetInstanceExtensionFieldGroupState> states = null;
            //Action act = async () =>
            //{
			var q = new AttributeSetInstanceExtensionFieldGroupsGetQuery();
			q.FirstResult = firstResult;
			q.MaxResults = maxResults;
            var req = new AttributeSetInstanceExtensionFieldGroupsGetRequest();
            req.Query = q;
            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroups.Get(req).GetAwaiter().GetResult();;
            states = resp.Content;
            //};
            //act();
            return states;
        }

        public IEnumerable<IAttributeSetInstanceExtensionFieldGroupState> Get(IDictionary<string, object> filter, IList<string> orders = null, int firstResult = 0, int maxResults = int.MaxValue)
        {//////////////////// todo ///////////////////////////
            IEnumerable<IAttributeSetInstanceExtensionFieldGroupState> states = null;
            //Action act = async () =>
            //{
			var q = new AttributeSetInstanceExtensionFieldGroupsGetQuery();
			q.FirstResult = firstResult;
			q.MaxResults = maxResults;
            var req = new AttributeSetInstanceExtensionFieldGroupsGetRequest();
            req.Query = q;
            var resp = _ramlClient.AttributeSetInstanceExtensionFieldGroups.Get(req).GetAwaiter().GetResult();;
            states = resp.Content;
            //};
            //act();
            return states;
        }

        public virtual void Execute(object command)
        {
            ((dynamic)this).When((dynamic)command);
        }



    }


    public partial class AttributeSetInstanceExtensionFieldGroupApplicationServiceProxyFactory : IAttributeSetInstanceExtensionFieldGroupApplicationServiceFactory
    {

        private string _endpointUrl;

        public AttributeSetInstanceExtensionFieldGroupApplicationServiceProxyFactory(string endpointUrl)
        {
            this._endpointUrl = endpointUrl;
        }

        public IAttributeSetInstanceExtensionFieldGroupApplicationService AttributeSetInstanceExtensionFieldGroupApplicationService
        {
            get
            {
                return new AttributeSetInstanceExtensionFieldGroupApplicationServiceProxy(_endpointUrl);
            }
        }

        public ICreateAttributeSetInstanceExtensionFieldGroup NewCreateAttributeSetInstanceExtensionFieldGroup()
        {
            return new CreateAttributeSetInstanceExtensionFieldGroupDto();
        }

        public IMergePatchAttributeSetInstanceExtensionFieldGroup NewMergePatchAttributeSetInstanceExtensionFieldGroup()
        {
            return new MergePatchAttributeSetInstanceExtensionFieldGroupDto();
        }

        public IDeleteAttributeSetInstanceExtensionFieldGroup NewDeleteAttributeSetInstanceExtensionFieldGroup()
        {
            return new DeleteAttributeSetInstanceExtensionFieldGroupDto();
        }
    }


}

