// <autogenerated>
//   This file was generated by T4 code generator GenerateAttributeSetInstancePropertyUtils.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Dddml.Wms.Domain;
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;


namespace Dddml.Wms.Support
{
    public static class AttributeSetInstancePropertyUtils
    {

        private static string GetSafeStringValue(string str)
        {
            if (str == null) { return "[null]"; }
            return str;
        }

        private static string GetMD5HashString(MD5 md5Hash, string input)
        {
            byte[] data = md5Hash.ComputeHash(Encoding.UTF8.GetBytes(input));
            StringBuilder sBuilder = new StringBuilder();
            for (int i = 0; i < data.Length; i++)
            {
                sBuilder.Append(data[i].ToString("x2"));
            }
            return sBuilder.ToString();
        }

        public static string GetHash(IAttributeSetInstanceStateProperties state)
        {
            StringBuilder sb = new StringBuilder();

            sb.Append("AttributeSetId").Append("=").Append(GetSafeStringValue(state.AttributeSetId)).Append("|");
            sb.Append("OrganizationId").Append("=").Append(GetSafeStringValue(state.OrganizationId)).Append("|");
            sb.Append("ReferenceId").Append("=").Append(GetSafeStringValue(state.ReferenceId)).Append("|");
            sb.Append("SerialNumber").Append("=").Append(GetSafeStringValue(state.SerialNumber)).Append("|");
            sb.Append("Lot").Append("=").Append(GetSafeStringValue(state.Lot)).Append("|");
            sb.Append("Description").Append("=").Append(GetSafeStringValue(state.Description)).Append("|");
            sb.Append("Active").Append("=").Append(state.Active).Append("|");
            sb.Append("_F_B_0_").Append("=").Append(state._F_B_0_).Append("|");
            sb.Append("_F_I_0_").Append("=").Append(state._F_I_0_).Append("|");
            sb.Append("_F_L_0_").Append("=").Append(state._F_L_0_).Append("|");
            sb.Append("_F_DT_0_").Append("=").Append(state._F_DT_0_).Append("|");
            sb.Append("_F_N_0_").Append("=").Append(state._F_N_0_).Append("|");
            sb.Append("_F_C5_0_").Append("=").Append(GetSafeStringValue(state._F_C5_0_)).Append("|");
            sb.Append("_F_C10_0_").Append("=").Append(GetSafeStringValue(state._F_C10_0_)).Append("|");
            sb.Append("_F_C20_0_").Append("=").Append(GetSafeStringValue(state._F_C20_0_)).Append("|");
            sb.Append("_F_C50_0_").Append("=").Append(GetSafeStringValue(state._F_C50_0_)).Append("|");
            sb.Append("_F_C100_0_").Append("=").Append(GetSafeStringValue(state._F_C100_0_)).Append("|");
            sb.Append("_F_C200_0_").Append("=").Append(GetSafeStringValue(state._F_C200_0_)).Append("|");
            sb.Append("_F_C500_0_").Append("=").Append(GetSafeStringValue(state._F_C500_0_)).Append("|");
            sb.Append("_F_C1000_0_").Append("=").Append(GetSafeStringValue(state._F_C1000_0_)).Append("|");
            sb.Append("_F_B_1_").Append("=").Append(state._F_B_1_).Append("|");
            sb.Append("_F_I_1_").Append("=").Append(state._F_I_1_).Append("|");
            sb.Append("_F_L_1_").Append("=").Append(state._F_L_1_).Append("|");
            sb.Append("_F_DT_1_").Append("=").Append(state._F_DT_1_).Append("|");
            sb.Append("_F_N_1_").Append("=").Append(state._F_N_1_).Append("|");
            sb.Append("_F_C5_1_").Append("=").Append(GetSafeStringValue(state._F_C5_1_)).Append("|");
            sb.Append("_F_C10_1_").Append("=").Append(GetSafeStringValue(state._F_C10_1_)).Append("|");
            sb.Append("_F_C20_1_").Append("=").Append(GetSafeStringValue(state._F_C20_1_)).Append("|");
            sb.Append("_F_C50_1_").Append("=").Append(GetSafeStringValue(state._F_C50_1_)).Append("|");
            sb.Append("_F_C100_1_").Append("=").Append(GetSafeStringValue(state._F_C100_1_)).Append("|");
            sb.Append("_F_C200_1_").Append("=").Append(GetSafeStringValue(state._F_C200_1_)).Append("|");
            sb.Append("_F_C500_1_").Append("=").Append(GetSafeStringValue(state._F_C500_1_)).Append("|");
            sb.Append("_F_C1000_1_").Append("=").Append(GetSafeStringValue(state._F_C1000_1_)).Append("|");
            sb.Append("_F_B_2_").Append("=").Append(state._F_B_2_).Append("|");
            sb.Append("_F_I_2_").Append("=").Append(state._F_I_2_).Append("|");
            sb.Append("_F_L_2_").Append("=").Append(state._F_L_2_).Append("|");
            sb.Append("_F_DT_2_").Append("=").Append(state._F_DT_2_).Append("|");
            sb.Append("_F_N_2_").Append("=").Append(state._F_N_2_).Append("|");
            sb.Append("_F_C5_2_").Append("=").Append(GetSafeStringValue(state._F_C5_2_)).Append("|");
            sb.Append("_F_C10_2_").Append("=").Append(GetSafeStringValue(state._F_C10_2_)).Append("|");
            sb.Append("_F_C20_2_").Append("=").Append(GetSafeStringValue(state._F_C20_2_)).Append("|");
            sb.Append("_F_C50_2_").Append("=").Append(GetSafeStringValue(state._F_C50_2_)).Append("|");
            sb.Append("_F_C100_2_").Append("=").Append(GetSafeStringValue(state._F_C100_2_)).Append("|");
            sb.Append("_F_C200_2_").Append("=").Append(GetSafeStringValue(state._F_C200_2_)).Append("|");
            sb.Append("_F_C500_2_").Append("=").Append(GetSafeStringValue(state._F_C500_2_)).Append("|");
            sb.Append("_F_C1000_2_").Append("=").Append(GetSafeStringValue(state._F_C1000_2_)).Append("|");
            sb.Append("_F_B_3_").Append("=").Append(state._F_B_3_).Append("|");
            sb.Append("_F_I_3_").Append("=").Append(state._F_I_3_).Append("|");
            sb.Append("_F_L_3_").Append("=").Append(state._F_L_3_).Append("|");
            sb.Append("_F_DT_3_").Append("=").Append(state._F_DT_3_).Append("|");
            sb.Append("_F_N_3_").Append("=").Append(state._F_N_3_).Append("|");
            sb.Append("_F_C5_3_").Append("=").Append(GetSafeStringValue(state._F_C5_3_)).Append("|");
            sb.Append("_F_C10_3_").Append("=").Append(GetSafeStringValue(state._F_C10_3_)).Append("|");
            sb.Append("_F_C20_3_").Append("=").Append(GetSafeStringValue(state._F_C20_3_)).Append("|");
            sb.Append("_F_C50_3_").Append("=").Append(GetSafeStringValue(state._F_C50_3_)).Append("|");
            sb.Append("_F_C100_3_").Append("=").Append(GetSafeStringValue(state._F_C100_3_)).Append("|");
            sb.Append("_F_C200_3_").Append("=").Append(GetSafeStringValue(state._F_C200_3_)).Append("|");
            sb.Append("_F_C500_3_").Append("=").Append(GetSafeStringValue(state._F_C500_3_)).Append("|");
            sb.Append("_F_C1000_3_").Append("=").Append(GetSafeStringValue(state._F_C1000_3_)).Append("|");
            sb.Append("_F_B_4_").Append("=").Append(state._F_B_4_).Append("|");
            sb.Append("_F_I_4_").Append("=").Append(state._F_I_4_).Append("|");
            sb.Append("_F_L_4_").Append("=").Append(state._F_L_4_).Append("|");
            sb.Append("_F_DT_4_").Append("=").Append(state._F_DT_4_).Append("|");
            sb.Append("_F_N_4_").Append("=").Append(state._F_N_4_).Append("|");
            sb.Append("_F_C5_4_").Append("=").Append(GetSafeStringValue(state._F_C5_4_)).Append("|");
            sb.Append("_F_C10_4_").Append("=").Append(GetSafeStringValue(state._F_C10_4_)).Append("|");
            sb.Append("_F_C20_4_").Append("=").Append(GetSafeStringValue(state._F_C20_4_)).Append("|");
            sb.Append("_F_C50_4_").Append("=").Append(GetSafeStringValue(state._F_C50_4_)).Append("|");
            sb.Append("_F_C100_4_").Append("=").Append(GetSafeStringValue(state._F_C100_4_)).Append("|");
            sb.Append("_F_C200_4_").Append("=").Append(GetSafeStringValue(state._F_C200_4_)).Append("|");
            sb.Append("_F_C500_4_").Append("=").Append(GetSafeStringValue(state._F_C500_4_)).Append("|");
            sb.Append("_F_C1000_4_").Append("=").Append(GetSafeStringValue(state._F_C1000_4_)).Append("|");
            sb.Append("_F_B_5_").Append("=").Append(state._F_B_5_).Append("|");
            sb.Append("_F_I_5_").Append("=").Append(state._F_I_5_).Append("|");
            sb.Append("_F_L_5_").Append("=").Append(state._F_L_5_).Append("|");
            sb.Append("_F_DT_5_").Append("=").Append(state._F_DT_5_).Append("|");
            sb.Append("_F_N_5_").Append("=").Append(state._F_N_5_).Append("|");
            sb.Append("_F_C5_5_").Append("=").Append(GetSafeStringValue(state._F_C5_5_)).Append("|");
            sb.Append("_F_C10_5_").Append("=").Append(GetSafeStringValue(state._F_C10_5_)).Append("|");
            sb.Append("_F_C20_5_").Append("=").Append(GetSafeStringValue(state._F_C20_5_)).Append("|");
            sb.Append("_F_C50_5_").Append("=").Append(GetSafeStringValue(state._F_C50_5_)).Append("|");
            sb.Append("_F_C100_5_").Append("=").Append(GetSafeStringValue(state._F_C100_5_)).Append("|");
            sb.Append("_F_C200_5_").Append("=").Append(GetSafeStringValue(state._F_C200_5_)).Append("|");
            sb.Append("_F_C500_5_").Append("=").Append(GetSafeStringValue(state._F_C500_5_)).Append("|");
            sb.Append("_F_B_6_").Append("=").Append(state._F_B_6_).Append("|");
            sb.Append("_F_I_6_").Append("=").Append(state._F_I_6_).Append("|");
            sb.Append("_F_L_6_").Append("=").Append(state._F_L_6_).Append("|");
            sb.Append("_F_DT_6_").Append("=").Append(state._F_DT_6_).Append("|");
            sb.Append("_F_N_6_").Append("=").Append(state._F_N_6_).Append("|");
            sb.Append("_F_C5_6_").Append("=").Append(GetSafeStringValue(state._F_C5_6_)).Append("|");
            sb.Append("_F_C10_6_").Append("=").Append(GetSafeStringValue(state._F_C10_6_)).Append("|");
            sb.Append("_F_C20_6_").Append("=").Append(GetSafeStringValue(state._F_C20_6_)).Append("|");
            sb.Append("_F_C50_6_").Append("=").Append(GetSafeStringValue(state._F_C50_6_)).Append("|");
            sb.Append("_F_C100_6_").Append("=").Append(GetSafeStringValue(state._F_C100_6_)).Append("|");
            sb.Append("_F_C200_6_").Append("=").Append(GetSafeStringValue(state._F_C200_6_)).Append("|");
            sb.Append("_F_C500_6_").Append("=").Append(GetSafeStringValue(state._F_C500_6_)).Append("|");
            sb.Append("_F_B_7_").Append("=").Append(state._F_B_7_).Append("|");
            sb.Append("_F_I_7_").Append("=").Append(state._F_I_7_).Append("|");
            sb.Append("_F_L_7_").Append("=").Append(state._F_L_7_).Append("|");
            sb.Append("_F_DT_7_").Append("=").Append(state._F_DT_7_).Append("|");
            sb.Append("_F_N_7_").Append("=").Append(state._F_N_7_).Append("|");
            sb.Append("_F_C5_7_").Append("=").Append(GetSafeStringValue(state._F_C5_7_)).Append("|");
            sb.Append("_F_C10_7_").Append("=").Append(GetSafeStringValue(state._F_C10_7_)).Append("|");
            sb.Append("_F_C20_7_").Append("=").Append(GetSafeStringValue(state._F_C20_7_)).Append("|");
            sb.Append("_F_C50_7_").Append("=").Append(GetSafeStringValue(state._F_C50_7_)).Append("|");
            sb.Append("_F_C100_7_").Append("=").Append(GetSafeStringValue(state._F_C100_7_)).Append("|");
            sb.Append("_F_C200_7_").Append("=").Append(GetSafeStringValue(state._F_C200_7_)).Append("|");
            sb.Append("_F_C500_7_").Append("=").Append(GetSafeStringValue(state._F_C500_7_)).Append("|");
            sb.Append("_F_B_8_").Append("=").Append(state._F_B_8_).Append("|");
            sb.Append("_F_I_8_").Append("=").Append(state._F_I_8_).Append("|");
            sb.Append("_F_L_8_").Append("=").Append(state._F_L_8_).Append("|");
            sb.Append("_F_DT_8_").Append("=").Append(state._F_DT_8_).Append("|");
            sb.Append("_F_N_8_").Append("=").Append(state._F_N_8_).Append("|");
            sb.Append("_F_C5_8_").Append("=").Append(GetSafeStringValue(state._F_C5_8_)).Append("|");
            sb.Append("_F_C10_8_").Append("=").Append(GetSafeStringValue(state._F_C10_8_)).Append("|");
            sb.Append("_F_C20_8_").Append("=").Append(GetSafeStringValue(state._F_C20_8_)).Append("|");
            sb.Append("_F_C50_8_").Append("=").Append(GetSafeStringValue(state._F_C50_8_)).Append("|");
            sb.Append("_F_C100_8_").Append("=").Append(GetSafeStringValue(state._F_C100_8_)).Append("|");
            sb.Append("_F_C200_8_").Append("=").Append(GetSafeStringValue(state._F_C200_8_)).Append("|");
            sb.Append("_F_C500_8_").Append("=").Append(GetSafeStringValue(state._F_C500_8_)).Append("|");
            sb.Append("_F_B_9_").Append("=").Append(state._F_B_9_).Append("|");
            sb.Append("_F_I_9_").Append("=").Append(state._F_I_9_).Append("|");
            sb.Append("_F_L_9_").Append("=").Append(state._F_L_9_).Append("|");
            sb.Append("_F_DT_9_").Append("=").Append(state._F_DT_9_).Append("|");
            sb.Append("_F_N_9_").Append("=").Append(state._F_N_9_).Append("|");
            sb.Append("_F_C5_9_").Append("=").Append(GetSafeStringValue(state._F_C5_9_)).Append("|");
            sb.Append("_F_C10_9_").Append("=").Append(GetSafeStringValue(state._F_C10_9_)).Append("|");
            sb.Append("_F_C20_9_").Append("=").Append(GetSafeStringValue(state._F_C20_9_)).Append("|");
            sb.Append("_F_C50_9_").Append("=").Append(GetSafeStringValue(state._F_C50_9_)).Append("|");
            sb.Append("_F_C100_9_").Append("=").Append(GetSafeStringValue(state._F_C100_9_)).Append("|");
            sb.Append("_F_C200_9_").Append("=").Append(GetSafeStringValue(state._F_C200_9_)).Append("|");
            sb.Append("_F_C500_9_").Append("=").Append(GetSafeStringValue(state._F_C500_9_)).Append("|");
            sb.Append("_F_B_10_").Append("=").Append(state._F_B_10_).Append("|");
            sb.Append("_F_I_10_").Append("=").Append(state._F_I_10_).Append("|");
            sb.Append("_F_L_10_").Append("=").Append(state._F_L_10_).Append("|");
            sb.Append("_F_DT_10_").Append("=").Append(state._F_DT_10_).Append("|");
            sb.Append("_F_N_10_").Append("=").Append(state._F_N_10_).Append("|");
            sb.Append("_F_C5_10_").Append("=").Append(GetSafeStringValue(state._F_C5_10_)).Append("|");
            sb.Append("_F_C10_10_").Append("=").Append(GetSafeStringValue(state._F_C10_10_)).Append("|");
            sb.Append("_F_C20_10_").Append("=").Append(GetSafeStringValue(state._F_C20_10_)).Append("|");
            sb.Append("_F_C50_10_").Append("=").Append(GetSafeStringValue(state._F_C50_10_)).Append("|");
            sb.Append("_F_C100_10_").Append("=").Append(GetSafeStringValue(state._F_C100_10_)).Append("|");
            sb.Append("_F_C200_10_").Append("=").Append(GetSafeStringValue(state._F_C200_10_)).Append("|");
            sb.Append("_F_B_11_").Append("=").Append(state._F_B_11_).Append("|");
            sb.Append("_F_I_11_").Append("=").Append(state._F_I_11_).Append("|");
            sb.Append("_F_L_11_").Append("=").Append(state._F_L_11_).Append("|");
            sb.Append("_F_DT_11_").Append("=").Append(state._F_DT_11_).Append("|");
            sb.Append("_F_N_11_").Append("=").Append(state._F_N_11_).Append("|");
            sb.Append("_F_C5_11_").Append("=").Append(GetSafeStringValue(state._F_C5_11_)).Append("|");
            sb.Append("_F_C10_11_").Append("=").Append(GetSafeStringValue(state._F_C10_11_)).Append("|");
            sb.Append("_F_C20_11_").Append("=").Append(GetSafeStringValue(state._F_C20_11_)).Append("|");
            sb.Append("_F_C50_11_").Append("=").Append(GetSafeStringValue(state._F_C50_11_)).Append("|");
            sb.Append("_F_C100_11_").Append("=").Append(GetSafeStringValue(state._F_C100_11_)).Append("|");
            sb.Append("_F_C200_11_").Append("=").Append(GetSafeStringValue(state._F_C200_11_)).Append("|");
            sb.Append("_F_B_12_").Append("=").Append(state._F_B_12_).Append("|");
            sb.Append("_F_I_12_").Append("=").Append(state._F_I_12_).Append("|");
            sb.Append("_F_L_12_").Append("=").Append(state._F_L_12_).Append("|");
            sb.Append("_F_DT_12_").Append("=").Append(state._F_DT_12_).Append("|");
            sb.Append("_F_N_12_").Append("=").Append(state._F_N_12_).Append("|");
            sb.Append("_F_C5_12_").Append("=").Append(GetSafeStringValue(state._F_C5_12_)).Append("|");
            sb.Append("_F_C10_12_").Append("=").Append(GetSafeStringValue(state._F_C10_12_)).Append("|");
            sb.Append("_F_C20_12_").Append("=").Append(GetSafeStringValue(state._F_C20_12_)).Append("|");
            sb.Append("_F_C50_12_").Append("=").Append(GetSafeStringValue(state._F_C50_12_)).Append("|");
            sb.Append("_F_C100_12_").Append("=").Append(GetSafeStringValue(state._F_C100_12_)).Append("|");
            sb.Append("_F_C200_12_").Append("=").Append(GetSafeStringValue(state._F_C200_12_)).Append("|");
            sb.Append("_F_B_13_").Append("=").Append(state._F_B_13_).Append("|");
            sb.Append("_F_I_13_").Append("=").Append(state._F_I_13_).Append("|");
            sb.Append("_F_L_13_").Append("=").Append(state._F_L_13_).Append("|");
            sb.Append("_F_DT_13_").Append("=").Append(state._F_DT_13_).Append("|");
            sb.Append("_F_N_13_").Append("=").Append(state._F_N_13_).Append("|");
            sb.Append("_F_C5_13_").Append("=").Append(GetSafeStringValue(state._F_C5_13_)).Append("|");
            sb.Append("_F_C10_13_").Append("=").Append(GetSafeStringValue(state._F_C10_13_)).Append("|");
            sb.Append("_F_C20_13_").Append("=").Append(GetSafeStringValue(state._F_C20_13_)).Append("|");
            sb.Append("_F_C50_13_").Append("=").Append(GetSafeStringValue(state._F_C50_13_)).Append("|");
            sb.Append("_F_C100_13_").Append("=").Append(GetSafeStringValue(state._F_C100_13_)).Append("|");
            sb.Append("_F_C200_13_").Append("=").Append(GetSafeStringValue(state._F_C200_13_)).Append("|");
            sb.Append("_F_B_14_").Append("=").Append(state._F_B_14_).Append("|");
            sb.Append("_F_I_14_").Append("=").Append(state._F_I_14_).Append("|");
            sb.Append("_F_L_14_").Append("=").Append(state._F_L_14_).Append("|");
            sb.Append("_F_DT_14_").Append("=").Append(state._F_DT_14_).Append("|");
            sb.Append("_F_N_14_").Append("=").Append(state._F_N_14_).Append("|");
            sb.Append("_F_C5_14_").Append("=").Append(GetSafeStringValue(state._F_C5_14_)).Append("|");
            sb.Append("_F_C10_14_").Append("=").Append(GetSafeStringValue(state._F_C10_14_)).Append("|");
            sb.Append("_F_C20_14_").Append("=").Append(GetSafeStringValue(state._F_C20_14_)).Append("|");
            sb.Append("_F_C50_14_").Append("=").Append(GetSafeStringValue(state._F_C50_14_)).Append("|");
            sb.Append("_F_C100_14_").Append("=").Append(GetSafeStringValue(state._F_C100_14_)).Append("|");
            sb.Append("_F_C200_14_").Append("=").Append(GetSafeStringValue(state._F_C200_14_)).Append("|");
            sb.Append("_F_B_15_").Append("=").Append(state._F_B_15_).Append("|");
            sb.Append("_F_I_15_").Append("=").Append(state._F_I_15_).Append("|");
            sb.Append("_F_L_15_").Append("=").Append(state._F_L_15_).Append("|");
            sb.Append("_F_DT_15_").Append("=").Append(state._F_DT_15_).Append("|");
            sb.Append("_F_N_15_").Append("=").Append(state._F_N_15_).Append("|");
            sb.Append("_F_C5_15_").Append("=").Append(GetSafeStringValue(state._F_C5_15_)).Append("|");
            sb.Append("_F_C10_15_").Append("=").Append(GetSafeStringValue(state._F_C10_15_)).Append("|");
            sb.Append("_F_C20_15_").Append("=").Append(GetSafeStringValue(state._F_C20_15_)).Append("|");
            sb.Append("_F_C50_15_").Append("=").Append(GetSafeStringValue(state._F_C50_15_)).Append("|");
            sb.Append("_F_C100_15_").Append("=").Append(GetSafeStringValue(state._F_C100_15_)).Append("|");
            sb.Append("_F_C200_15_").Append("=").Append(GetSafeStringValue(state._F_C200_15_)).Append("|");
            sb.Append("_F_B_16_").Append("=").Append(state._F_B_16_).Append("|");
            sb.Append("_F_I_16_").Append("=").Append(state._F_I_16_).Append("|");
            sb.Append("_F_L_16_").Append("=").Append(state._F_L_16_).Append("|");
            sb.Append("_F_DT_16_").Append("=").Append(state._F_DT_16_).Append("|");
            sb.Append("_F_N_16_").Append("=").Append(state._F_N_16_).Append("|");
            sb.Append("_F_C5_16_").Append("=").Append(GetSafeStringValue(state._F_C5_16_)).Append("|");
            sb.Append("_F_C10_16_").Append("=").Append(GetSafeStringValue(state._F_C10_16_)).Append("|");
            sb.Append("_F_C20_16_").Append("=").Append(GetSafeStringValue(state._F_C20_16_)).Append("|");
            sb.Append("_F_C50_16_").Append("=").Append(GetSafeStringValue(state._F_C50_16_)).Append("|");
            sb.Append("_F_C100_16_").Append("=").Append(GetSafeStringValue(state._F_C100_16_)).Append("|");
            sb.Append("_F_C200_16_").Append("=").Append(GetSafeStringValue(state._F_C200_16_)).Append("|");
            sb.Append("_F_B_17_").Append("=").Append(state._F_B_17_).Append("|");
            sb.Append("_F_I_17_").Append("=").Append(state._F_I_17_).Append("|");
            sb.Append("_F_L_17_").Append("=").Append(state._F_L_17_).Append("|");
            sb.Append("_F_DT_17_").Append("=").Append(state._F_DT_17_).Append("|");
            sb.Append("_F_N_17_").Append("=").Append(state._F_N_17_).Append("|");
            sb.Append("_F_C5_17_").Append("=").Append(GetSafeStringValue(state._F_C5_17_)).Append("|");
            sb.Append("_F_C10_17_").Append("=").Append(GetSafeStringValue(state._F_C10_17_)).Append("|");
            sb.Append("_F_C20_17_").Append("=").Append(GetSafeStringValue(state._F_C20_17_)).Append("|");
            sb.Append("_F_C50_17_").Append("=").Append(GetSafeStringValue(state._F_C50_17_)).Append("|");
            sb.Append("_F_C100_17_").Append("=").Append(GetSafeStringValue(state._F_C100_17_)).Append("|");
            sb.Append("_F_C200_17_").Append("=").Append(GetSafeStringValue(state._F_C200_17_)).Append("|");
            sb.Append("_F_B_18_").Append("=").Append(state._F_B_18_).Append("|");
            sb.Append("_F_I_18_").Append("=").Append(state._F_I_18_).Append("|");
            sb.Append("_F_L_18_").Append("=").Append(state._F_L_18_).Append("|");
            sb.Append("_F_DT_18_").Append("=").Append(state._F_DT_18_).Append("|");
            sb.Append("_F_N_18_").Append("=").Append(state._F_N_18_).Append("|");
            sb.Append("_F_C5_18_").Append("=").Append(GetSafeStringValue(state._F_C5_18_)).Append("|");
            sb.Append("_F_C10_18_").Append("=").Append(GetSafeStringValue(state._F_C10_18_)).Append("|");
            sb.Append("_F_C20_18_").Append("=").Append(GetSafeStringValue(state._F_C20_18_)).Append("|");
            sb.Append("_F_C50_18_").Append("=").Append(GetSafeStringValue(state._F_C50_18_)).Append("|");
            sb.Append("_F_C100_18_").Append("=").Append(GetSafeStringValue(state._F_C100_18_)).Append("|");
            sb.Append("_F_C200_18_").Append("=").Append(GetSafeStringValue(state._F_C200_18_)).Append("|");
            sb.Append("_F_B_19_").Append("=").Append(state._F_B_19_).Append("|");
            sb.Append("_F_I_19_").Append("=").Append(state._F_I_19_).Append("|");
            sb.Append("_F_L_19_").Append("=").Append(state._F_L_19_).Append("|");
            sb.Append("_F_DT_19_").Append("=").Append(state._F_DT_19_).Append("|");
            sb.Append("_F_N_19_").Append("=").Append(state._F_N_19_).Append("|");
            sb.Append("_F_C5_19_").Append("=").Append(GetSafeStringValue(state._F_C5_19_)).Append("|");
            sb.Append("_F_C10_19_").Append("=").Append(GetSafeStringValue(state._F_C10_19_)).Append("|");
            sb.Append("_F_C20_19_").Append("=").Append(GetSafeStringValue(state._F_C20_19_)).Append("|");
            sb.Append("_F_C50_19_").Append("=").Append(GetSafeStringValue(state._F_C50_19_)).Append("|");
            sb.Append("_F_C100_19_").Append("=").Append(GetSafeStringValue(state._F_C100_19_)).Append("|");
            sb.Append("_F_C200_19_").Append("=").Append(GetSafeStringValue(state._F_C200_19_)).Append("|");
            sb.Append("_F_B_20_").Append("=").Append(state._F_B_20_).Append("|");
            sb.Append("_F_I_20_").Append("=").Append(state._F_I_20_).Append("|");
            sb.Append("_F_L_20_").Append("=").Append(state._F_L_20_).Append("|");
            sb.Append("_F_N_20_").Append("=").Append(state._F_N_20_).Append("|");
            sb.Append("_F_C5_20_").Append("=").Append(GetSafeStringValue(state._F_C5_20_)).Append("|");
            sb.Append("_F_C10_20_").Append("=").Append(GetSafeStringValue(state._F_C10_20_)).Append("|");
            sb.Append("_F_C20_20_").Append("=").Append(GetSafeStringValue(state._F_C20_20_)).Append("|");
            sb.Append("_F_C50_20_").Append("=").Append(GetSafeStringValue(state._F_C50_20_)).Append("|");
            sb.Append("_F_B_21_").Append("=").Append(state._F_B_21_).Append("|");
            sb.Append("_F_I_21_").Append("=").Append(state._F_I_21_).Append("|");
            sb.Append("_F_L_21_").Append("=").Append(state._F_L_21_).Append("|");
            sb.Append("_F_N_21_").Append("=").Append(state._F_N_21_).Append("|");
            sb.Append("_F_C5_21_").Append("=").Append(GetSafeStringValue(state._F_C5_21_)).Append("|");
            sb.Append("_F_C10_21_").Append("=").Append(GetSafeStringValue(state._F_C10_21_)).Append("|");
            sb.Append("_F_C20_21_").Append("=").Append(GetSafeStringValue(state._F_C20_21_)).Append("|");
            sb.Append("_F_C50_21_").Append("=").Append(GetSafeStringValue(state._F_C50_21_)).Append("|");
            sb.Append("_F_B_22_").Append("=").Append(state._F_B_22_).Append("|");
            sb.Append("_F_I_22_").Append("=").Append(state._F_I_22_).Append("|");
            sb.Append("_F_L_22_").Append("=").Append(state._F_L_22_).Append("|");
            sb.Append("_F_N_22_").Append("=").Append(state._F_N_22_).Append("|");
            sb.Append("_F_C5_22_").Append("=").Append(GetSafeStringValue(state._F_C5_22_)).Append("|");
            sb.Append("_F_C10_22_").Append("=").Append(GetSafeStringValue(state._F_C10_22_)).Append("|");
            sb.Append("_F_C20_22_").Append("=").Append(GetSafeStringValue(state._F_C20_22_)).Append("|");
            sb.Append("_F_C50_22_").Append("=").Append(GetSafeStringValue(state._F_C50_22_)).Append("|");
            sb.Append("_F_B_23_").Append("=").Append(state._F_B_23_).Append("|");
            sb.Append("_F_I_23_").Append("=").Append(state._F_I_23_).Append("|");
            sb.Append("_F_L_23_").Append("=").Append(state._F_L_23_).Append("|");
            sb.Append("_F_N_23_").Append("=").Append(state._F_N_23_).Append("|");
            sb.Append("_F_C5_23_").Append("=").Append(GetSafeStringValue(state._F_C5_23_)).Append("|");
            sb.Append("_F_C10_23_").Append("=").Append(GetSafeStringValue(state._F_C10_23_)).Append("|");
            sb.Append("_F_C20_23_").Append("=").Append(GetSafeStringValue(state._F_C20_23_)).Append("|");
            sb.Append("_F_C50_23_").Append("=").Append(GetSafeStringValue(state._F_C50_23_)).Append("|");
            sb.Append("_F_B_24_").Append("=").Append(state._F_B_24_).Append("|");
            sb.Append("_F_I_24_").Append("=").Append(state._F_I_24_).Append("|");
            sb.Append("_F_L_24_").Append("=").Append(state._F_L_24_).Append("|");
            sb.Append("_F_N_24_").Append("=").Append(state._F_N_24_).Append("|");
            sb.Append("_F_C5_24_").Append("=").Append(GetSafeStringValue(state._F_C5_24_)).Append("|");
            sb.Append("_F_C10_24_").Append("=").Append(GetSafeStringValue(state._F_C10_24_)).Append("|");
            sb.Append("_F_C20_24_").Append("=").Append(GetSafeStringValue(state._F_C20_24_)).Append("|");
            sb.Append("_F_C50_24_").Append("=").Append(GetSafeStringValue(state._F_C50_24_)).Append("|");
            sb.Append("_F_B_25_").Append("=").Append(state._F_B_25_).Append("|");
            sb.Append("_F_I_25_").Append("=").Append(state._F_I_25_).Append("|");
            sb.Append("_F_L_25_").Append("=").Append(state._F_L_25_).Append("|");
            sb.Append("_F_N_25_").Append("=").Append(state._F_N_25_).Append("|");
            sb.Append("_F_C5_25_").Append("=").Append(GetSafeStringValue(state._F_C5_25_)).Append("|");
            sb.Append("_F_C10_25_").Append("=").Append(GetSafeStringValue(state._F_C10_25_)).Append("|");
            sb.Append("_F_C20_25_").Append("=").Append(GetSafeStringValue(state._F_C20_25_)).Append("|");
            sb.Append("_F_C50_25_").Append("=").Append(GetSafeStringValue(state._F_C50_25_)).Append("|");
            sb.Append("_F_B_26_").Append("=").Append(state._F_B_26_).Append("|");
            sb.Append("_F_I_26_").Append("=").Append(state._F_I_26_).Append("|");
            sb.Append("_F_L_26_").Append("=").Append(state._F_L_26_).Append("|");
            sb.Append("_F_N_26_").Append("=").Append(state._F_N_26_).Append("|");
            sb.Append("_F_C5_26_").Append("=").Append(GetSafeStringValue(state._F_C5_26_)).Append("|");
            sb.Append("_F_C10_26_").Append("=").Append(GetSafeStringValue(state._F_C10_26_)).Append("|");
            sb.Append("_F_C20_26_").Append("=").Append(GetSafeStringValue(state._F_C20_26_)).Append("|");
            sb.Append("_F_C50_26_").Append("=").Append(GetSafeStringValue(state._F_C50_26_)).Append("|");
            sb.Append("_F_B_27_").Append("=").Append(state._F_B_27_).Append("|");
            sb.Append("_F_I_27_").Append("=").Append(state._F_I_27_).Append("|");
            sb.Append("_F_L_27_").Append("=").Append(state._F_L_27_).Append("|");
            sb.Append("_F_N_27_").Append("=").Append(state._F_N_27_).Append("|");
            sb.Append("_F_C5_27_").Append("=").Append(GetSafeStringValue(state._F_C5_27_)).Append("|");
            sb.Append("_F_C10_27_").Append("=").Append(GetSafeStringValue(state._F_C10_27_)).Append("|");
            sb.Append("_F_C20_27_").Append("=").Append(GetSafeStringValue(state._F_C20_27_)).Append("|");
            sb.Append("_F_C50_27_").Append("=").Append(GetSafeStringValue(state._F_C50_27_)).Append("|");
            sb.Append("_F_B_28_").Append("=").Append(state._F_B_28_).Append("|");
            sb.Append("_F_I_28_").Append("=").Append(state._F_I_28_).Append("|");
            sb.Append("_F_L_28_").Append("=").Append(state._F_L_28_).Append("|");
            sb.Append("_F_N_28_").Append("=").Append(state._F_N_28_).Append("|");
            sb.Append("_F_C5_28_").Append("=").Append(GetSafeStringValue(state._F_C5_28_)).Append("|");
            sb.Append("_F_C10_28_").Append("=").Append(GetSafeStringValue(state._F_C10_28_)).Append("|");
            sb.Append("_F_C20_28_").Append("=").Append(GetSafeStringValue(state._F_C20_28_)).Append("|");
            sb.Append("_F_C50_28_").Append("=").Append(GetSafeStringValue(state._F_C50_28_)).Append("|");
            sb.Append("_F_B_29_").Append("=").Append(state._F_B_29_).Append("|");
            sb.Append("_F_I_29_").Append("=").Append(state._F_I_29_).Append("|");
            sb.Append("_F_L_29_").Append("=").Append(state._F_L_29_).Append("|");
            sb.Append("_F_N_29_").Append("=").Append(state._F_N_29_).Append("|");
            sb.Append("_F_C5_29_").Append("=").Append(GetSafeStringValue(state._F_C5_29_)).Append("|");
            sb.Append("_F_C10_29_").Append("=").Append(GetSafeStringValue(state._F_C10_29_)).Append("|");
            sb.Append("_F_C20_29_").Append("=").Append(GetSafeStringValue(state._F_C20_29_)).Append("|");
            sb.Append("_F_C50_29_").Append("=").Append(GetSafeStringValue(state._F_C50_29_)).Append("|");
            sb.Append("_F_B_30_").Append("=").Append(state._F_B_30_).Append("|");
            sb.Append("_F_I_30_").Append("=").Append(state._F_I_30_).Append("|");
            sb.Append("_F_N_30_").Append("=").Append(state._F_N_30_).Append("|");
            sb.Append("_F_C5_30_").Append("=").Append(GetSafeStringValue(state._F_C5_30_)).Append("|");
            sb.Append("_F_C10_30_").Append("=").Append(GetSafeStringValue(state._F_C10_30_)).Append("|");
            sb.Append("_F_C20_30_").Append("=").Append(GetSafeStringValue(state._F_C20_30_)).Append("|");
            sb.Append("_F_C50_30_").Append("=").Append(GetSafeStringValue(state._F_C50_30_)).Append("|");
            sb.Append("_F_B_31_").Append("=").Append(state._F_B_31_).Append("|");
            sb.Append("_F_I_31_").Append("=").Append(state._F_I_31_).Append("|");
            sb.Append("_F_N_31_").Append("=").Append(state._F_N_31_).Append("|");
            sb.Append("_F_C5_31_").Append("=").Append(GetSafeStringValue(state._F_C5_31_)).Append("|");
            sb.Append("_F_C10_31_").Append("=").Append(GetSafeStringValue(state._F_C10_31_)).Append("|");
            sb.Append("_F_C20_31_").Append("=").Append(GetSafeStringValue(state._F_C20_31_)).Append("|");
            sb.Append("_F_C50_31_").Append("=").Append(GetSafeStringValue(state._F_C50_31_)).Append("|");
            sb.Append("_F_B_32_").Append("=").Append(state._F_B_32_).Append("|");
            sb.Append("_F_I_32_").Append("=").Append(state._F_I_32_).Append("|");
            sb.Append("_F_N_32_").Append("=").Append(state._F_N_32_).Append("|");
            sb.Append("_F_C5_32_").Append("=").Append(GetSafeStringValue(state._F_C5_32_)).Append("|");
            sb.Append("_F_C10_32_").Append("=").Append(GetSafeStringValue(state._F_C10_32_)).Append("|");
            sb.Append("_F_C20_32_").Append("=").Append(GetSafeStringValue(state._F_C20_32_)).Append("|");
            sb.Append("_F_C50_32_").Append("=").Append(GetSafeStringValue(state._F_C50_32_)).Append("|");
            sb.Append("_F_B_33_").Append("=").Append(state._F_B_33_).Append("|");
            sb.Append("_F_I_33_").Append("=").Append(state._F_I_33_).Append("|");
            sb.Append("_F_N_33_").Append("=").Append(state._F_N_33_).Append("|");
            sb.Append("_F_C5_33_").Append("=").Append(GetSafeStringValue(state._F_C5_33_)).Append("|");
            sb.Append("_F_C10_33_").Append("=").Append(GetSafeStringValue(state._F_C10_33_)).Append("|");
            sb.Append("_F_C20_33_").Append("=").Append(GetSafeStringValue(state._F_C20_33_)).Append("|");
            sb.Append("_F_C50_33_").Append("=").Append(GetSafeStringValue(state._F_C50_33_)).Append("|");
            sb.Append("_F_B_34_").Append("=").Append(state._F_B_34_).Append("|");
            sb.Append("_F_I_34_").Append("=").Append(state._F_I_34_).Append("|");
            sb.Append("_F_N_34_").Append("=").Append(state._F_N_34_).Append("|");
            sb.Append("_F_C5_34_").Append("=").Append(GetSafeStringValue(state._F_C5_34_)).Append("|");
            sb.Append("_F_C10_34_").Append("=").Append(GetSafeStringValue(state._F_C10_34_)).Append("|");
            sb.Append("_F_C20_34_").Append("=").Append(GetSafeStringValue(state._F_C20_34_)).Append("|");
            sb.Append("_F_C50_34_").Append("=").Append(GetSafeStringValue(state._F_C50_34_)).Append("|");
            sb.Append("_F_B_35_").Append("=").Append(state._F_B_35_).Append("|");
            sb.Append("_F_I_35_").Append("=").Append(state._F_I_35_).Append("|");
            sb.Append("_F_N_35_").Append("=").Append(state._F_N_35_).Append("|");
            sb.Append("_F_C5_35_").Append("=").Append(GetSafeStringValue(state._F_C5_35_)).Append("|");
            sb.Append("_F_C10_35_").Append("=").Append(GetSafeStringValue(state._F_C10_35_)).Append("|");
            sb.Append("_F_C20_35_").Append("=").Append(GetSafeStringValue(state._F_C20_35_)).Append("|");
            sb.Append("_F_C50_35_").Append("=").Append(GetSafeStringValue(state._F_C50_35_)).Append("|");
            sb.Append("_F_B_36_").Append("=").Append(state._F_B_36_).Append("|");
            sb.Append("_F_I_36_").Append("=").Append(state._F_I_36_).Append("|");
            sb.Append("_F_N_36_").Append("=").Append(state._F_N_36_).Append("|");
            sb.Append("_F_C5_36_").Append("=").Append(GetSafeStringValue(state._F_C5_36_)).Append("|");
            sb.Append("_F_C10_36_").Append("=").Append(GetSafeStringValue(state._F_C10_36_)).Append("|");
            sb.Append("_F_C20_36_").Append("=").Append(GetSafeStringValue(state._F_C20_36_)).Append("|");
            sb.Append("_F_C50_36_").Append("=").Append(GetSafeStringValue(state._F_C50_36_)).Append("|");
            sb.Append("_F_B_37_").Append("=").Append(state._F_B_37_).Append("|");
            sb.Append("_F_I_37_").Append("=").Append(state._F_I_37_).Append("|");
            sb.Append("_F_N_37_").Append("=").Append(state._F_N_37_).Append("|");
            sb.Append("_F_C5_37_").Append("=").Append(GetSafeStringValue(state._F_C5_37_)).Append("|");
            sb.Append("_F_C10_37_").Append("=").Append(GetSafeStringValue(state._F_C10_37_)).Append("|");
            sb.Append("_F_C20_37_").Append("=").Append(GetSafeStringValue(state._F_C20_37_)).Append("|");
            sb.Append("_F_C50_37_").Append("=").Append(GetSafeStringValue(state._F_C50_37_)).Append("|");
            sb.Append("_F_B_38_").Append("=").Append(state._F_B_38_).Append("|");
            sb.Append("_F_I_38_").Append("=").Append(state._F_I_38_).Append("|");
            sb.Append("_F_N_38_").Append("=").Append(state._F_N_38_).Append("|");
            sb.Append("_F_C5_38_").Append("=").Append(GetSafeStringValue(state._F_C5_38_)).Append("|");
            sb.Append("_F_C10_38_").Append("=").Append(GetSafeStringValue(state._F_C10_38_)).Append("|");
            sb.Append("_F_C20_38_").Append("=").Append(GetSafeStringValue(state._F_C20_38_)).Append("|");
            sb.Append("_F_C50_38_").Append("=").Append(GetSafeStringValue(state._F_C50_38_)).Append("|");
            sb.Append("_F_B_39_").Append("=").Append(state._F_B_39_).Append("|");
            sb.Append("_F_I_39_").Append("=").Append(state._F_I_39_).Append("|");
            sb.Append("_F_N_39_").Append("=").Append(state._F_N_39_).Append("|");
            sb.Append("_F_C5_39_").Append("=").Append(GetSafeStringValue(state._F_C5_39_)).Append("|");
            sb.Append("_F_C10_39_").Append("=").Append(GetSafeStringValue(state._F_C10_39_)).Append("|");
            sb.Append("_F_C20_39_").Append("=").Append(GetSafeStringValue(state._F_C20_39_)).Append("|");
            sb.Append("_F_C50_39_").Append("=").Append(GetSafeStringValue(state._F_C50_39_)).Append("|");
            sb.Append("_F_B_40_").Append("=").Append(state._F_B_40_).Append("|");
            sb.Append("_F_I_40_").Append("=").Append(state._F_I_40_).Append("|");
            sb.Append("_F_N_40_").Append("=").Append(state._F_N_40_).Append("|");
            sb.Append("_F_C5_40_").Append("=").Append(GetSafeStringValue(state._F_C5_40_)).Append("|");
            sb.Append("_F_C10_40_").Append("=").Append(GetSafeStringValue(state._F_C10_40_)).Append("|");
            sb.Append("_F_C20_40_").Append("=").Append(GetSafeStringValue(state._F_C20_40_)).Append("|");
            sb.Append("_F_C50_40_").Append("=").Append(GetSafeStringValue(state._F_C50_40_)).Append("|");
            sb.Append("_F_B_41_").Append("=").Append(state._F_B_41_).Append("|");
            sb.Append("_F_I_41_").Append("=").Append(state._F_I_41_).Append("|");
            sb.Append("_F_N_41_").Append("=").Append(state._F_N_41_).Append("|");
            sb.Append("_F_C5_41_").Append("=").Append(GetSafeStringValue(state._F_C5_41_)).Append("|");
            sb.Append("_F_C10_41_").Append("=").Append(GetSafeStringValue(state._F_C10_41_)).Append("|");
            sb.Append("_F_C20_41_").Append("=").Append(GetSafeStringValue(state._F_C20_41_)).Append("|");
            sb.Append("_F_C50_41_").Append("=").Append(GetSafeStringValue(state._F_C50_41_)).Append("|");
            sb.Append("_F_B_42_").Append("=").Append(state._F_B_42_).Append("|");
            sb.Append("_F_I_42_").Append("=").Append(state._F_I_42_).Append("|");
            sb.Append("_F_N_42_").Append("=").Append(state._F_N_42_).Append("|");
            sb.Append("_F_C5_42_").Append("=").Append(GetSafeStringValue(state._F_C5_42_)).Append("|");
            sb.Append("_F_C10_42_").Append("=").Append(GetSafeStringValue(state._F_C10_42_)).Append("|");
            sb.Append("_F_C20_42_").Append("=").Append(GetSafeStringValue(state._F_C20_42_)).Append("|");
            sb.Append("_F_C50_42_").Append("=").Append(GetSafeStringValue(state._F_C50_42_)).Append("|");
            sb.Append("_F_B_43_").Append("=").Append(state._F_B_43_).Append("|");
            sb.Append("_F_I_43_").Append("=").Append(state._F_I_43_).Append("|");
            sb.Append("_F_N_43_").Append("=").Append(state._F_N_43_).Append("|");
            sb.Append("_F_C5_43_").Append("=").Append(GetSafeStringValue(state._F_C5_43_)).Append("|");
            sb.Append("_F_C10_43_").Append("=").Append(GetSafeStringValue(state._F_C10_43_)).Append("|");
            sb.Append("_F_C20_43_").Append("=").Append(GetSafeStringValue(state._F_C20_43_)).Append("|");
            sb.Append("_F_C50_43_").Append("=").Append(GetSafeStringValue(state._F_C50_43_)).Append("|");
            sb.Append("_F_B_44_").Append("=").Append(state._F_B_44_).Append("|");
            sb.Append("_F_I_44_").Append("=").Append(state._F_I_44_).Append("|");
            sb.Append("_F_N_44_").Append("=").Append(state._F_N_44_).Append("|");
            sb.Append("_F_C5_44_").Append("=").Append(GetSafeStringValue(state._F_C5_44_)).Append("|");
            sb.Append("_F_C10_44_").Append("=").Append(GetSafeStringValue(state._F_C10_44_)).Append("|");
            sb.Append("_F_C20_44_").Append("=").Append(GetSafeStringValue(state._F_C20_44_)).Append("|");
            sb.Append("_F_C50_44_").Append("=").Append(GetSafeStringValue(state._F_C50_44_)).Append("|");
            sb.Append("_F_B_45_").Append("=").Append(state._F_B_45_).Append("|");
            sb.Append("_F_I_45_").Append("=").Append(state._F_I_45_).Append("|");
            sb.Append("_F_N_45_").Append("=").Append(state._F_N_45_).Append("|");
            sb.Append("_F_C5_45_").Append("=").Append(GetSafeStringValue(state._F_C5_45_)).Append("|");
            sb.Append("_F_C10_45_").Append("=").Append(GetSafeStringValue(state._F_C10_45_)).Append("|");
            sb.Append("_F_C20_45_").Append("=").Append(GetSafeStringValue(state._F_C20_45_)).Append("|");
            sb.Append("_F_C50_45_").Append("=").Append(GetSafeStringValue(state._F_C50_45_)).Append("|");
            sb.Append("_F_B_46_").Append("=").Append(state._F_B_46_).Append("|");
            sb.Append("_F_I_46_").Append("=").Append(state._F_I_46_).Append("|");
            sb.Append("_F_N_46_").Append("=").Append(state._F_N_46_).Append("|");
            sb.Append("_F_C5_46_").Append("=").Append(GetSafeStringValue(state._F_C5_46_)).Append("|");
            sb.Append("_F_C10_46_").Append("=").Append(GetSafeStringValue(state._F_C10_46_)).Append("|");
            sb.Append("_F_C20_46_").Append("=").Append(GetSafeStringValue(state._F_C20_46_)).Append("|");
            sb.Append("_F_C50_46_").Append("=").Append(GetSafeStringValue(state._F_C50_46_)).Append("|");
            sb.Append("_F_B_47_").Append("=").Append(state._F_B_47_).Append("|");
            sb.Append("_F_I_47_").Append("=").Append(state._F_I_47_).Append("|");
            sb.Append("_F_N_47_").Append("=").Append(state._F_N_47_).Append("|");
            sb.Append("_F_C5_47_").Append("=").Append(GetSafeStringValue(state._F_C5_47_)).Append("|");
            sb.Append("_F_C10_47_").Append("=").Append(GetSafeStringValue(state._F_C10_47_)).Append("|");
            sb.Append("_F_C20_47_").Append("=").Append(GetSafeStringValue(state._F_C20_47_)).Append("|");
            sb.Append("_F_C50_47_").Append("=").Append(GetSafeStringValue(state._F_C50_47_)).Append("|");
            sb.Append("_F_B_48_").Append("=").Append(state._F_B_48_).Append("|");
            sb.Append("_F_I_48_").Append("=").Append(state._F_I_48_).Append("|");
            sb.Append("_F_N_48_").Append("=").Append(state._F_N_48_).Append("|");
            sb.Append("_F_C5_48_").Append("=").Append(GetSafeStringValue(state._F_C5_48_)).Append("|");
            sb.Append("_F_C10_48_").Append("=").Append(GetSafeStringValue(state._F_C10_48_)).Append("|");
            sb.Append("_F_C20_48_").Append("=").Append(GetSafeStringValue(state._F_C20_48_)).Append("|");
            sb.Append("_F_C50_48_").Append("=").Append(GetSafeStringValue(state._F_C50_48_)).Append("|");
            sb.Append("_F_B_49_").Append("=").Append(state._F_B_49_).Append("|");
            sb.Append("_F_I_49_").Append("=").Append(state._F_I_49_).Append("|");
            sb.Append("_F_N_49_").Append("=").Append(state._F_N_49_).Append("|");
            sb.Append("_F_C5_49_").Append("=").Append(GetSafeStringValue(state._F_C5_49_)).Append("|");
            sb.Append("_F_C10_49_").Append("=").Append(GetSafeStringValue(state._F_C10_49_)).Append("|");
            sb.Append("_F_C20_49_").Append("=").Append(GetSafeStringValue(state._F_C20_49_)).Append("|");
            sb.Append("_F_C50_49_").Append("=").Append(GetSafeStringValue(state._F_C50_49_)).Append("|");

            using (MD5 md5Hash = MD5.Create())
            {
                string hash = GetMD5HashString(md5Hash, sb.ToString());
                return hash;
            }
        }

        public static bool Equals(IAttributeSetInstanceStateProperties state1, IAttributeSetInstanceStateProperties state2)
        {
            if (!Object.Equals(state1.AttributeSetId, state2.AttributeSetId)
                || !Object.Equals(state1.OrganizationId, state2.OrganizationId)
                || !Object.Equals(state1.ReferenceId, state2.ReferenceId)
                || !Object.Equals(state1.SerialNumber, state2.SerialNumber)
                || !Object.Equals(state1.Lot, state2.Lot)
                || !Object.Equals(state1.Description, state2.Description)
                || !Object.Equals(state1.Active, state2.Active)
                || !Object.Equals(state1._F_B_0_, state2._F_B_0_)
                || !Object.Equals(state1._F_I_0_, state2._F_I_0_)
                || !Object.Equals(state1._F_L_0_, state2._F_L_0_)
                || !Object.Equals(state1._F_DT_0_, state2._F_DT_0_)
                || !Object.Equals(state1._F_N_0_, state2._F_N_0_)
                || !Object.Equals(state1._F_C5_0_, state2._F_C5_0_)
                || !Object.Equals(state1._F_C10_0_, state2._F_C10_0_)
                || !Object.Equals(state1._F_C20_0_, state2._F_C20_0_)
                || !Object.Equals(state1._F_C50_0_, state2._F_C50_0_)
                || !Object.Equals(state1._F_C100_0_, state2._F_C100_0_)
                || !Object.Equals(state1._F_C200_0_, state2._F_C200_0_)
                || !Object.Equals(state1._F_C500_0_, state2._F_C500_0_)
                || !Object.Equals(state1._F_C1000_0_, state2._F_C1000_0_)
                || !Object.Equals(state1._F_B_1_, state2._F_B_1_)
                || !Object.Equals(state1._F_I_1_, state2._F_I_1_)
                || !Object.Equals(state1._F_L_1_, state2._F_L_1_)
                || !Object.Equals(state1._F_DT_1_, state2._F_DT_1_)
                || !Object.Equals(state1._F_N_1_, state2._F_N_1_)
                || !Object.Equals(state1._F_C5_1_, state2._F_C5_1_)
                || !Object.Equals(state1._F_C10_1_, state2._F_C10_1_)
                || !Object.Equals(state1._F_C20_1_, state2._F_C20_1_)
                || !Object.Equals(state1._F_C50_1_, state2._F_C50_1_)
                || !Object.Equals(state1._F_C100_1_, state2._F_C100_1_)
                || !Object.Equals(state1._F_C200_1_, state2._F_C200_1_)
                || !Object.Equals(state1._F_C500_1_, state2._F_C500_1_)
                || !Object.Equals(state1._F_C1000_1_, state2._F_C1000_1_)
                || !Object.Equals(state1._F_B_2_, state2._F_B_2_)
                || !Object.Equals(state1._F_I_2_, state2._F_I_2_)
                || !Object.Equals(state1._F_L_2_, state2._F_L_2_)
                || !Object.Equals(state1._F_DT_2_, state2._F_DT_2_)
                || !Object.Equals(state1._F_N_2_, state2._F_N_2_)
                || !Object.Equals(state1._F_C5_2_, state2._F_C5_2_)
                || !Object.Equals(state1._F_C10_2_, state2._F_C10_2_)
                || !Object.Equals(state1._F_C20_2_, state2._F_C20_2_)
                || !Object.Equals(state1._F_C50_2_, state2._F_C50_2_)
                || !Object.Equals(state1._F_C100_2_, state2._F_C100_2_)
                || !Object.Equals(state1._F_C200_2_, state2._F_C200_2_)
                || !Object.Equals(state1._F_C500_2_, state2._F_C500_2_)
                || !Object.Equals(state1._F_C1000_2_, state2._F_C1000_2_)
                || !Object.Equals(state1._F_B_3_, state2._F_B_3_)
                || !Object.Equals(state1._F_I_3_, state2._F_I_3_)
                || !Object.Equals(state1._F_L_3_, state2._F_L_3_)
                || !Object.Equals(state1._F_DT_3_, state2._F_DT_3_)
                || !Object.Equals(state1._F_N_3_, state2._F_N_3_)
                || !Object.Equals(state1._F_C5_3_, state2._F_C5_3_)
                || !Object.Equals(state1._F_C10_3_, state2._F_C10_3_)
                || !Object.Equals(state1._F_C20_3_, state2._F_C20_3_)
                || !Object.Equals(state1._F_C50_3_, state2._F_C50_3_)
                || !Object.Equals(state1._F_C100_3_, state2._F_C100_3_)
                || !Object.Equals(state1._F_C200_3_, state2._F_C200_3_)
                || !Object.Equals(state1._F_C500_3_, state2._F_C500_3_)
                || !Object.Equals(state1._F_C1000_3_, state2._F_C1000_3_)
                || !Object.Equals(state1._F_B_4_, state2._F_B_4_)
                || !Object.Equals(state1._F_I_4_, state2._F_I_4_)
                || !Object.Equals(state1._F_L_4_, state2._F_L_4_)
                || !Object.Equals(state1._F_DT_4_, state2._F_DT_4_)
                || !Object.Equals(state1._F_N_4_, state2._F_N_4_)
                || !Object.Equals(state1._F_C5_4_, state2._F_C5_4_)
                || !Object.Equals(state1._F_C10_4_, state2._F_C10_4_)
                || !Object.Equals(state1._F_C20_4_, state2._F_C20_4_)
                || !Object.Equals(state1._F_C50_4_, state2._F_C50_4_)
                || !Object.Equals(state1._F_C100_4_, state2._F_C100_4_)
                || !Object.Equals(state1._F_C200_4_, state2._F_C200_4_)
                || !Object.Equals(state1._F_C500_4_, state2._F_C500_4_)
                || !Object.Equals(state1._F_C1000_4_, state2._F_C1000_4_)
                || !Object.Equals(state1._F_B_5_, state2._F_B_5_)
                || !Object.Equals(state1._F_I_5_, state2._F_I_5_)
                || !Object.Equals(state1._F_L_5_, state2._F_L_5_)
                || !Object.Equals(state1._F_DT_5_, state2._F_DT_5_)
                || !Object.Equals(state1._F_N_5_, state2._F_N_5_)
                || !Object.Equals(state1._F_C5_5_, state2._F_C5_5_)
                || !Object.Equals(state1._F_C10_5_, state2._F_C10_5_)
                || !Object.Equals(state1._F_C20_5_, state2._F_C20_5_)
                || !Object.Equals(state1._F_C50_5_, state2._F_C50_5_)
                || !Object.Equals(state1._F_C100_5_, state2._F_C100_5_)
                || !Object.Equals(state1._F_C200_5_, state2._F_C200_5_)
                || !Object.Equals(state1._F_C500_5_, state2._F_C500_5_)
                || !Object.Equals(state1._F_B_6_, state2._F_B_6_)
                || !Object.Equals(state1._F_I_6_, state2._F_I_6_)
                || !Object.Equals(state1._F_L_6_, state2._F_L_6_)
                || !Object.Equals(state1._F_DT_6_, state2._F_DT_6_)
                || !Object.Equals(state1._F_N_6_, state2._F_N_6_)
                || !Object.Equals(state1._F_C5_6_, state2._F_C5_6_)
                || !Object.Equals(state1._F_C10_6_, state2._F_C10_6_)
                || !Object.Equals(state1._F_C20_6_, state2._F_C20_6_)
                || !Object.Equals(state1._F_C50_6_, state2._F_C50_6_)
                || !Object.Equals(state1._F_C100_6_, state2._F_C100_6_)
                || !Object.Equals(state1._F_C200_6_, state2._F_C200_6_)
                || !Object.Equals(state1._F_C500_6_, state2._F_C500_6_)
                || !Object.Equals(state1._F_B_7_, state2._F_B_7_)
                || !Object.Equals(state1._F_I_7_, state2._F_I_7_)
                || !Object.Equals(state1._F_L_7_, state2._F_L_7_)
                || !Object.Equals(state1._F_DT_7_, state2._F_DT_7_)
                || !Object.Equals(state1._F_N_7_, state2._F_N_7_)
                || !Object.Equals(state1._F_C5_7_, state2._F_C5_7_)
                || !Object.Equals(state1._F_C10_7_, state2._F_C10_7_)
                || !Object.Equals(state1._F_C20_7_, state2._F_C20_7_)
                || !Object.Equals(state1._F_C50_7_, state2._F_C50_7_)
                || !Object.Equals(state1._F_C100_7_, state2._F_C100_7_)
                || !Object.Equals(state1._F_C200_7_, state2._F_C200_7_)
                || !Object.Equals(state1._F_C500_7_, state2._F_C500_7_)
                || !Object.Equals(state1._F_B_8_, state2._F_B_8_)
                || !Object.Equals(state1._F_I_8_, state2._F_I_8_)
                || !Object.Equals(state1._F_L_8_, state2._F_L_8_)
                || !Object.Equals(state1._F_DT_8_, state2._F_DT_8_)
                || !Object.Equals(state1._F_N_8_, state2._F_N_8_)
                || !Object.Equals(state1._F_C5_8_, state2._F_C5_8_)
                || !Object.Equals(state1._F_C10_8_, state2._F_C10_8_)
                || !Object.Equals(state1._F_C20_8_, state2._F_C20_8_)
                || !Object.Equals(state1._F_C50_8_, state2._F_C50_8_)
                || !Object.Equals(state1._F_C100_8_, state2._F_C100_8_)
                || !Object.Equals(state1._F_C200_8_, state2._F_C200_8_)
                || !Object.Equals(state1._F_C500_8_, state2._F_C500_8_)
                || !Object.Equals(state1._F_B_9_, state2._F_B_9_)
                || !Object.Equals(state1._F_I_9_, state2._F_I_9_)
                || !Object.Equals(state1._F_L_9_, state2._F_L_9_)
                || !Object.Equals(state1._F_DT_9_, state2._F_DT_9_)
                || !Object.Equals(state1._F_N_9_, state2._F_N_9_)
                || !Object.Equals(state1._F_C5_9_, state2._F_C5_9_)
                || !Object.Equals(state1._F_C10_9_, state2._F_C10_9_)
                || !Object.Equals(state1._F_C20_9_, state2._F_C20_9_)
                || !Object.Equals(state1._F_C50_9_, state2._F_C50_9_)
                || !Object.Equals(state1._F_C100_9_, state2._F_C100_9_)
                || !Object.Equals(state1._F_C200_9_, state2._F_C200_9_)
                || !Object.Equals(state1._F_C500_9_, state2._F_C500_9_)
                || !Object.Equals(state1._F_B_10_, state2._F_B_10_)
                || !Object.Equals(state1._F_I_10_, state2._F_I_10_)
                || !Object.Equals(state1._F_L_10_, state2._F_L_10_)
                || !Object.Equals(state1._F_DT_10_, state2._F_DT_10_)
                || !Object.Equals(state1._F_N_10_, state2._F_N_10_)
                || !Object.Equals(state1._F_C5_10_, state2._F_C5_10_)
                || !Object.Equals(state1._F_C10_10_, state2._F_C10_10_)
                || !Object.Equals(state1._F_C20_10_, state2._F_C20_10_)
                || !Object.Equals(state1._F_C50_10_, state2._F_C50_10_)
                || !Object.Equals(state1._F_C100_10_, state2._F_C100_10_)
                || !Object.Equals(state1._F_C200_10_, state2._F_C200_10_)
                || !Object.Equals(state1._F_B_11_, state2._F_B_11_)
                || !Object.Equals(state1._F_I_11_, state2._F_I_11_)
                || !Object.Equals(state1._F_L_11_, state2._F_L_11_)
                || !Object.Equals(state1._F_DT_11_, state2._F_DT_11_)
                || !Object.Equals(state1._F_N_11_, state2._F_N_11_)
                || !Object.Equals(state1._F_C5_11_, state2._F_C5_11_)
                || !Object.Equals(state1._F_C10_11_, state2._F_C10_11_)
                || !Object.Equals(state1._F_C20_11_, state2._F_C20_11_)
                || !Object.Equals(state1._F_C50_11_, state2._F_C50_11_)
                || !Object.Equals(state1._F_C100_11_, state2._F_C100_11_)
                || !Object.Equals(state1._F_C200_11_, state2._F_C200_11_)
                || !Object.Equals(state1._F_B_12_, state2._F_B_12_)
                || !Object.Equals(state1._F_I_12_, state2._F_I_12_)
                || !Object.Equals(state1._F_L_12_, state2._F_L_12_)
                || !Object.Equals(state1._F_DT_12_, state2._F_DT_12_)
                || !Object.Equals(state1._F_N_12_, state2._F_N_12_)
                || !Object.Equals(state1._F_C5_12_, state2._F_C5_12_)
                || !Object.Equals(state1._F_C10_12_, state2._F_C10_12_)
                || !Object.Equals(state1._F_C20_12_, state2._F_C20_12_)
                || !Object.Equals(state1._F_C50_12_, state2._F_C50_12_)
                || !Object.Equals(state1._F_C100_12_, state2._F_C100_12_)
                || !Object.Equals(state1._F_C200_12_, state2._F_C200_12_)
                || !Object.Equals(state1._F_B_13_, state2._F_B_13_)
                || !Object.Equals(state1._F_I_13_, state2._F_I_13_)
                || !Object.Equals(state1._F_L_13_, state2._F_L_13_)
                || !Object.Equals(state1._F_DT_13_, state2._F_DT_13_)
                || !Object.Equals(state1._F_N_13_, state2._F_N_13_)
                || !Object.Equals(state1._F_C5_13_, state2._F_C5_13_)
                || !Object.Equals(state1._F_C10_13_, state2._F_C10_13_)
                || !Object.Equals(state1._F_C20_13_, state2._F_C20_13_)
                || !Object.Equals(state1._F_C50_13_, state2._F_C50_13_)
                || !Object.Equals(state1._F_C100_13_, state2._F_C100_13_)
                || !Object.Equals(state1._F_C200_13_, state2._F_C200_13_)
                || !Object.Equals(state1._F_B_14_, state2._F_B_14_)
                || !Object.Equals(state1._F_I_14_, state2._F_I_14_)
                || !Object.Equals(state1._F_L_14_, state2._F_L_14_)
                || !Object.Equals(state1._F_DT_14_, state2._F_DT_14_)
                || !Object.Equals(state1._F_N_14_, state2._F_N_14_)
                || !Object.Equals(state1._F_C5_14_, state2._F_C5_14_)
                || !Object.Equals(state1._F_C10_14_, state2._F_C10_14_)
                || !Object.Equals(state1._F_C20_14_, state2._F_C20_14_)
                || !Object.Equals(state1._F_C50_14_, state2._F_C50_14_)
                || !Object.Equals(state1._F_C100_14_, state2._F_C100_14_)
                || !Object.Equals(state1._F_C200_14_, state2._F_C200_14_)
                || !Object.Equals(state1._F_B_15_, state2._F_B_15_)
                || !Object.Equals(state1._F_I_15_, state2._F_I_15_)
                || !Object.Equals(state1._F_L_15_, state2._F_L_15_)
                || !Object.Equals(state1._F_DT_15_, state2._F_DT_15_)
                || !Object.Equals(state1._F_N_15_, state2._F_N_15_)
                || !Object.Equals(state1._F_C5_15_, state2._F_C5_15_)
                || !Object.Equals(state1._F_C10_15_, state2._F_C10_15_)
                || !Object.Equals(state1._F_C20_15_, state2._F_C20_15_)
                || !Object.Equals(state1._F_C50_15_, state2._F_C50_15_)
                || !Object.Equals(state1._F_C100_15_, state2._F_C100_15_)
                || !Object.Equals(state1._F_C200_15_, state2._F_C200_15_)
                || !Object.Equals(state1._F_B_16_, state2._F_B_16_)
                || !Object.Equals(state1._F_I_16_, state2._F_I_16_)
                || !Object.Equals(state1._F_L_16_, state2._F_L_16_)
                || !Object.Equals(state1._F_DT_16_, state2._F_DT_16_)
                || !Object.Equals(state1._F_N_16_, state2._F_N_16_)
                || !Object.Equals(state1._F_C5_16_, state2._F_C5_16_)
                || !Object.Equals(state1._F_C10_16_, state2._F_C10_16_)
                || !Object.Equals(state1._F_C20_16_, state2._F_C20_16_)
                || !Object.Equals(state1._F_C50_16_, state2._F_C50_16_)
                || !Object.Equals(state1._F_C100_16_, state2._F_C100_16_)
                || !Object.Equals(state1._F_C200_16_, state2._F_C200_16_)
                || !Object.Equals(state1._F_B_17_, state2._F_B_17_)
                || !Object.Equals(state1._F_I_17_, state2._F_I_17_)
                || !Object.Equals(state1._F_L_17_, state2._F_L_17_)
                || !Object.Equals(state1._F_DT_17_, state2._F_DT_17_)
                || !Object.Equals(state1._F_N_17_, state2._F_N_17_)
                || !Object.Equals(state1._F_C5_17_, state2._F_C5_17_)
                || !Object.Equals(state1._F_C10_17_, state2._F_C10_17_)
                || !Object.Equals(state1._F_C20_17_, state2._F_C20_17_)
                || !Object.Equals(state1._F_C50_17_, state2._F_C50_17_)
                || !Object.Equals(state1._F_C100_17_, state2._F_C100_17_)
                || !Object.Equals(state1._F_C200_17_, state2._F_C200_17_)
                || !Object.Equals(state1._F_B_18_, state2._F_B_18_)
                || !Object.Equals(state1._F_I_18_, state2._F_I_18_)
                || !Object.Equals(state1._F_L_18_, state2._F_L_18_)
                || !Object.Equals(state1._F_DT_18_, state2._F_DT_18_)
                || !Object.Equals(state1._F_N_18_, state2._F_N_18_)
                || !Object.Equals(state1._F_C5_18_, state2._F_C5_18_)
                || !Object.Equals(state1._F_C10_18_, state2._F_C10_18_)
                || !Object.Equals(state1._F_C20_18_, state2._F_C20_18_)
                || !Object.Equals(state1._F_C50_18_, state2._F_C50_18_)
                || !Object.Equals(state1._F_C100_18_, state2._F_C100_18_)
                || !Object.Equals(state1._F_C200_18_, state2._F_C200_18_)
                || !Object.Equals(state1._F_B_19_, state2._F_B_19_)
                || !Object.Equals(state1._F_I_19_, state2._F_I_19_)
                || !Object.Equals(state1._F_L_19_, state2._F_L_19_)
                || !Object.Equals(state1._F_DT_19_, state2._F_DT_19_)
                || !Object.Equals(state1._F_N_19_, state2._F_N_19_)
                || !Object.Equals(state1._F_C5_19_, state2._F_C5_19_)
                || !Object.Equals(state1._F_C10_19_, state2._F_C10_19_)
                || !Object.Equals(state1._F_C20_19_, state2._F_C20_19_)
                || !Object.Equals(state1._F_C50_19_, state2._F_C50_19_)
                || !Object.Equals(state1._F_C100_19_, state2._F_C100_19_)
                || !Object.Equals(state1._F_C200_19_, state2._F_C200_19_)
                || !Object.Equals(state1._F_B_20_, state2._F_B_20_)
                || !Object.Equals(state1._F_I_20_, state2._F_I_20_)
                || !Object.Equals(state1._F_L_20_, state2._F_L_20_)
                || !Object.Equals(state1._F_N_20_, state2._F_N_20_)
                || !Object.Equals(state1._F_C5_20_, state2._F_C5_20_)
                || !Object.Equals(state1._F_C10_20_, state2._F_C10_20_)
                || !Object.Equals(state1._F_C20_20_, state2._F_C20_20_)
                || !Object.Equals(state1._F_C50_20_, state2._F_C50_20_)
                || !Object.Equals(state1._F_B_21_, state2._F_B_21_)
                || !Object.Equals(state1._F_I_21_, state2._F_I_21_)
                || !Object.Equals(state1._F_L_21_, state2._F_L_21_)
                || !Object.Equals(state1._F_N_21_, state2._F_N_21_)
                || !Object.Equals(state1._F_C5_21_, state2._F_C5_21_)
                || !Object.Equals(state1._F_C10_21_, state2._F_C10_21_)
                || !Object.Equals(state1._F_C20_21_, state2._F_C20_21_)
                || !Object.Equals(state1._F_C50_21_, state2._F_C50_21_)
                || !Object.Equals(state1._F_B_22_, state2._F_B_22_)
                || !Object.Equals(state1._F_I_22_, state2._F_I_22_)
                || !Object.Equals(state1._F_L_22_, state2._F_L_22_)
                || !Object.Equals(state1._F_N_22_, state2._F_N_22_)
                || !Object.Equals(state1._F_C5_22_, state2._F_C5_22_)
                || !Object.Equals(state1._F_C10_22_, state2._F_C10_22_)
                || !Object.Equals(state1._F_C20_22_, state2._F_C20_22_)
                || !Object.Equals(state1._F_C50_22_, state2._F_C50_22_)
                || !Object.Equals(state1._F_B_23_, state2._F_B_23_)
                || !Object.Equals(state1._F_I_23_, state2._F_I_23_)
                || !Object.Equals(state1._F_L_23_, state2._F_L_23_)
                || !Object.Equals(state1._F_N_23_, state2._F_N_23_)
                || !Object.Equals(state1._F_C5_23_, state2._F_C5_23_)
                || !Object.Equals(state1._F_C10_23_, state2._F_C10_23_)
                || !Object.Equals(state1._F_C20_23_, state2._F_C20_23_)
                || !Object.Equals(state1._F_C50_23_, state2._F_C50_23_)
                || !Object.Equals(state1._F_B_24_, state2._F_B_24_)
                || !Object.Equals(state1._F_I_24_, state2._F_I_24_)
                || !Object.Equals(state1._F_L_24_, state2._F_L_24_)
                || !Object.Equals(state1._F_N_24_, state2._F_N_24_)
                || !Object.Equals(state1._F_C5_24_, state2._F_C5_24_)
                || !Object.Equals(state1._F_C10_24_, state2._F_C10_24_)
                || !Object.Equals(state1._F_C20_24_, state2._F_C20_24_)
                || !Object.Equals(state1._F_C50_24_, state2._F_C50_24_)
                || !Object.Equals(state1._F_B_25_, state2._F_B_25_)
                || !Object.Equals(state1._F_I_25_, state2._F_I_25_)
                || !Object.Equals(state1._F_L_25_, state2._F_L_25_)
                || !Object.Equals(state1._F_N_25_, state2._F_N_25_)
                || !Object.Equals(state1._F_C5_25_, state2._F_C5_25_)
                || !Object.Equals(state1._F_C10_25_, state2._F_C10_25_)
                || !Object.Equals(state1._F_C20_25_, state2._F_C20_25_)
                || !Object.Equals(state1._F_C50_25_, state2._F_C50_25_)
                || !Object.Equals(state1._F_B_26_, state2._F_B_26_)
                || !Object.Equals(state1._F_I_26_, state2._F_I_26_)
                || !Object.Equals(state1._F_L_26_, state2._F_L_26_)
                || !Object.Equals(state1._F_N_26_, state2._F_N_26_)
                || !Object.Equals(state1._F_C5_26_, state2._F_C5_26_)
                || !Object.Equals(state1._F_C10_26_, state2._F_C10_26_)
                || !Object.Equals(state1._F_C20_26_, state2._F_C20_26_)
                || !Object.Equals(state1._F_C50_26_, state2._F_C50_26_)
                || !Object.Equals(state1._F_B_27_, state2._F_B_27_)
                || !Object.Equals(state1._F_I_27_, state2._F_I_27_)
                || !Object.Equals(state1._F_L_27_, state2._F_L_27_)
                || !Object.Equals(state1._F_N_27_, state2._F_N_27_)
                || !Object.Equals(state1._F_C5_27_, state2._F_C5_27_)
                || !Object.Equals(state1._F_C10_27_, state2._F_C10_27_)
                || !Object.Equals(state1._F_C20_27_, state2._F_C20_27_)
                || !Object.Equals(state1._F_C50_27_, state2._F_C50_27_)
                || !Object.Equals(state1._F_B_28_, state2._F_B_28_)
                || !Object.Equals(state1._F_I_28_, state2._F_I_28_)
                || !Object.Equals(state1._F_L_28_, state2._F_L_28_)
                || !Object.Equals(state1._F_N_28_, state2._F_N_28_)
                || !Object.Equals(state1._F_C5_28_, state2._F_C5_28_)
                || !Object.Equals(state1._F_C10_28_, state2._F_C10_28_)
                || !Object.Equals(state1._F_C20_28_, state2._F_C20_28_)
                || !Object.Equals(state1._F_C50_28_, state2._F_C50_28_)
                || !Object.Equals(state1._F_B_29_, state2._F_B_29_)
                || !Object.Equals(state1._F_I_29_, state2._F_I_29_)
                || !Object.Equals(state1._F_L_29_, state2._F_L_29_)
                || !Object.Equals(state1._F_N_29_, state2._F_N_29_)
                || !Object.Equals(state1._F_C5_29_, state2._F_C5_29_)
                || !Object.Equals(state1._F_C10_29_, state2._F_C10_29_)
                || !Object.Equals(state1._F_C20_29_, state2._F_C20_29_)
                || !Object.Equals(state1._F_C50_29_, state2._F_C50_29_)
                || !Object.Equals(state1._F_B_30_, state2._F_B_30_)
                || !Object.Equals(state1._F_I_30_, state2._F_I_30_)
                || !Object.Equals(state1._F_N_30_, state2._F_N_30_)
                || !Object.Equals(state1._F_C5_30_, state2._F_C5_30_)
                || !Object.Equals(state1._F_C10_30_, state2._F_C10_30_)
                || !Object.Equals(state1._F_C20_30_, state2._F_C20_30_)
                || !Object.Equals(state1._F_C50_30_, state2._F_C50_30_)
                || !Object.Equals(state1._F_B_31_, state2._F_B_31_)
                || !Object.Equals(state1._F_I_31_, state2._F_I_31_)
                || !Object.Equals(state1._F_N_31_, state2._F_N_31_)
                || !Object.Equals(state1._F_C5_31_, state2._F_C5_31_)
                || !Object.Equals(state1._F_C10_31_, state2._F_C10_31_)
                || !Object.Equals(state1._F_C20_31_, state2._F_C20_31_)
                || !Object.Equals(state1._F_C50_31_, state2._F_C50_31_)
                || !Object.Equals(state1._F_B_32_, state2._F_B_32_)
                || !Object.Equals(state1._F_I_32_, state2._F_I_32_)
                || !Object.Equals(state1._F_N_32_, state2._F_N_32_)
                || !Object.Equals(state1._F_C5_32_, state2._F_C5_32_)
                || !Object.Equals(state1._F_C10_32_, state2._F_C10_32_)
                || !Object.Equals(state1._F_C20_32_, state2._F_C20_32_)
                || !Object.Equals(state1._F_C50_32_, state2._F_C50_32_)
                || !Object.Equals(state1._F_B_33_, state2._F_B_33_)
                || !Object.Equals(state1._F_I_33_, state2._F_I_33_)
                || !Object.Equals(state1._F_N_33_, state2._F_N_33_)
                || !Object.Equals(state1._F_C5_33_, state2._F_C5_33_)
                || !Object.Equals(state1._F_C10_33_, state2._F_C10_33_)
                || !Object.Equals(state1._F_C20_33_, state2._F_C20_33_)
                || !Object.Equals(state1._F_C50_33_, state2._F_C50_33_)
                || !Object.Equals(state1._F_B_34_, state2._F_B_34_)
                || !Object.Equals(state1._F_I_34_, state2._F_I_34_)
                || !Object.Equals(state1._F_N_34_, state2._F_N_34_)
                || !Object.Equals(state1._F_C5_34_, state2._F_C5_34_)
                || !Object.Equals(state1._F_C10_34_, state2._F_C10_34_)
                || !Object.Equals(state1._F_C20_34_, state2._F_C20_34_)
                || !Object.Equals(state1._F_C50_34_, state2._F_C50_34_)
                || !Object.Equals(state1._F_B_35_, state2._F_B_35_)
                || !Object.Equals(state1._F_I_35_, state2._F_I_35_)
                || !Object.Equals(state1._F_N_35_, state2._F_N_35_)
                || !Object.Equals(state1._F_C5_35_, state2._F_C5_35_)
                || !Object.Equals(state1._F_C10_35_, state2._F_C10_35_)
                || !Object.Equals(state1._F_C20_35_, state2._F_C20_35_)
                || !Object.Equals(state1._F_C50_35_, state2._F_C50_35_)
                || !Object.Equals(state1._F_B_36_, state2._F_B_36_)
                || !Object.Equals(state1._F_I_36_, state2._F_I_36_)
                || !Object.Equals(state1._F_N_36_, state2._F_N_36_)
                || !Object.Equals(state1._F_C5_36_, state2._F_C5_36_)
                || !Object.Equals(state1._F_C10_36_, state2._F_C10_36_)
                || !Object.Equals(state1._F_C20_36_, state2._F_C20_36_)
                || !Object.Equals(state1._F_C50_36_, state2._F_C50_36_)
                || !Object.Equals(state1._F_B_37_, state2._F_B_37_)
                || !Object.Equals(state1._F_I_37_, state2._F_I_37_)
                || !Object.Equals(state1._F_N_37_, state2._F_N_37_)
                || !Object.Equals(state1._F_C5_37_, state2._F_C5_37_)
                || !Object.Equals(state1._F_C10_37_, state2._F_C10_37_)
                || !Object.Equals(state1._F_C20_37_, state2._F_C20_37_)
                || !Object.Equals(state1._F_C50_37_, state2._F_C50_37_)
                || !Object.Equals(state1._F_B_38_, state2._F_B_38_)
                || !Object.Equals(state1._F_I_38_, state2._F_I_38_)
                || !Object.Equals(state1._F_N_38_, state2._F_N_38_)
                || !Object.Equals(state1._F_C5_38_, state2._F_C5_38_)
                || !Object.Equals(state1._F_C10_38_, state2._F_C10_38_)
                || !Object.Equals(state1._F_C20_38_, state2._F_C20_38_)
                || !Object.Equals(state1._F_C50_38_, state2._F_C50_38_)
                || !Object.Equals(state1._F_B_39_, state2._F_B_39_)
                || !Object.Equals(state1._F_I_39_, state2._F_I_39_)
                || !Object.Equals(state1._F_N_39_, state2._F_N_39_)
                || !Object.Equals(state1._F_C5_39_, state2._F_C5_39_)
                || !Object.Equals(state1._F_C10_39_, state2._F_C10_39_)
                || !Object.Equals(state1._F_C20_39_, state2._F_C20_39_)
                || !Object.Equals(state1._F_C50_39_, state2._F_C50_39_)
                || !Object.Equals(state1._F_B_40_, state2._F_B_40_)
                || !Object.Equals(state1._F_I_40_, state2._F_I_40_)
                || !Object.Equals(state1._F_N_40_, state2._F_N_40_)
                || !Object.Equals(state1._F_C5_40_, state2._F_C5_40_)
                || !Object.Equals(state1._F_C10_40_, state2._F_C10_40_)
                || !Object.Equals(state1._F_C20_40_, state2._F_C20_40_)
                || !Object.Equals(state1._F_C50_40_, state2._F_C50_40_)
                || !Object.Equals(state1._F_B_41_, state2._F_B_41_)
                || !Object.Equals(state1._F_I_41_, state2._F_I_41_)
                || !Object.Equals(state1._F_N_41_, state2._F_N_41_)
                || !Object.Equals(state1._F_C5_41_, state2._F_C5_41_)
                || !Object.Equals(state1._F_C10_41_, state2._F_C10_41_)
                || !Object.Equals(state1._F_C20_41_, state2._F_C20_41_)
                || !Object.Equals(state1._F_C50_41_, state2._F_C50_41_)
                || !Object.Equals(state1._F_B_42_, state2._F_B_42_)
                || !Object.Equals(state1._F_I_42_, state2._F_I_42_)
                || !Object.Equals(state1._F_N_42_, state2._F_N_42_)
                || !Object.Equals(state1._F_C5_42_, state2._F_C5_42_)
                || !Object.Equals(state1._F_C10_42_, state2._F_C10_42_)
                || !Object.Equals(state1._F_C20_42_, state2._F_C20_42_)
                || !Object.Equals(state1._F_C50_42_, state2._F_C50_42_)
                || !Object.Equals(state1._F_B_43_, state2._F_B_43_)
                || !Object.Equals(state1._F_I_43_, state2._F_I_43_)
                || !Object.Equals(state1._F_N_43_, state2._F_N_43_)
                || !Object.Equals(state1._F_C5_43_, state2._F_C5_43_)
                || !Object.Equals(state1._F_C10_43_, state2._F_C10_43_)
                || !Object.Equals(state1._F_C20_43_, state2._F_C20_43_)
                || !Object.Equals(state1._F_C50_43_, state2._F_C50_43_)
                || !Object.Equals(state1._F_B_44_, state2._F_B_44_)
                || !Object.Equals(state1._F_I_44_, state2._F_I_44_)
                || !Object.Equals(state1._F_N_44_, state2._F_N_44_)
                || !Object.Equals(state1._F_C5_44_, state2._F_C5_44_)
                || !Object.Equals(state1._F_C10_44_, state2._F_C10_44_)
                || !Object.Equals(state1._F_C20_44_, state2._F_C20_44_)
                || !Object.Equals(state1._F_C50_44_, state2._F_C50_44_)
                || !Object.Equals(state1._F_B_45_, state2._F_B_45_)
                || !Object.Equals(state1._F_I_45_, state2._F_I_45_)
                || !Object.Equals(state1._F_N_45_, state2._F_N_45_)
                || !Object.Equals(state1._F_C5_45_, state2._F_C5_45_)
                || !Object.Equals(state1._F_C10_45_, state2._F_C10_45_)
                || !Object.Equals(state1._F_C20_45_, state2._F_C20_45_)
                || !Object.Equals(state1._F_C50_45_, state2._F_C50_45_)
                || !Object.Equals(state1._F_B_46_, state2._F_B_46_)
                || !Object.Equals(state1._F_I_46_, state2._F_I_46_)
                || !Object.Equals(state1._F_N_46_, state2._F_N_46_)
                || !Object.Equals(state1._F_C5_46_, state2._F_C5_46_)
                || !Object.Equals(state1._F_C10_46_, state2._F_C10_46_)
                || !Object.Equals(state1._F_C20_46_, state2._F_C20_46_)
                || !Object.Equals(state1._F_C50_46_, state2._F_C50_46_)
                || !Object.Equals(state1._F_B_47_, state2._F_B_47_)
                || !Object.Equals(state1._F_I_47_, state2._F_I_47_)
                || !Object.Equals(state1._F_N_47_, state2._F_N_47_)
                || !Object.Equals(state1._F_C5_47_, state2._F_C5_47_)
                || !Object.Equals(state1._F_C10_47_, state2._F_C10_47_)
                || !Object.Equals(state1._F_C20_47_, state2._F_C20_47_)
                || !Object.Equals(state1._F_C50_47_, state2._F_C50_47_)
                || !Object.Equals(state1._F_B_48_, state2._F_B_48_)
                || !Object.Equals(state1._F_I_48_, state2._F_I_48_)
                || !Object.Equals(state1._F_N_48_, state2._F_N_48_)
                || !Object.Equals(state1._F_C5_48_, state2._F_C5_48_)
                || !Object.Equals(state1._F_C10_48_, state2._F_C10_48_)
                || !Object.Equals(state1._F_C20_48_, state2._F_C20_48_)
                || !Object.Equals(state1._F_C50_48_, state2._F_C50_48_)
                || !Object.Equals(state1._F_B_49_, state2._F_B_49_)
                || !Object.Equals(state1._F_I_49_, state2._F_I_49_)
                || !Object.Equals(state1._F_N_49_, state2._F_N_49_)
                || !Object.Equals(state1._F_C5_49_, state2._F_C5_49_)
                || !Object.Equals(state1._F_C10_49_, state2._F_C10_49_)
                || !Object.Equals(state1._F_C20_49_, state2._F_C20_49_)
                || !Object.Equals(state1._F_C50_49_, state2._F_C50_49_)
                )
            {
                return false;
            }
            return true;
        }


    }

}


