package org.dddml.wms.domain.meta;

import java.util.HashMap;
import java.util.Map;

public final class InOutLineMvoFilteringProperties
{

    private InOutLineMvoFilteringProperties()
    {
    }

    public final static String[] propertyNames = new String[] {
            "LineNumber",
            "Description",
            "LocatorId",
            "Product",
            "UomId",
            "MovementQuantity",
            "ConfirmedQuantity",
            "ScrappedQuantity",
            "TargetQuantity",
            "PickedQuantity",
            "IsInvoiced",
            "AttributeSetInstanceId",
            "IsDescription",
            "Processed",
            "QuantityEntered",
            "RmaLineNumber",
            "ReversalLineNumber",
            "Version",
            "CreatedBy",
            "CreatedAt",
            "UpdatedBy",
            "UpdatedAt",
            "Active",
            "Deleted",
            "InOutIsSOTransaction",
            "InOutDocumentStatus",
            "InOutPosted",
            "InOutProcessing",
            "InOutProcessed",
            "InOutDocumentType",
            "InOutDescription",
            "InOutOrderNumber",
            "InOutDateOrdered",
            "InOutIsPrinted",
            "InOutMovementType",
            "InOutMovementDate",
            "InOutBusinessPartnerId",
            "InOutWarehouseId",
            "InOutPOReference",
            "InOutFreightAmount",
            "InOutShipperId",
            "InOutChargeAmount",
            "InOutDatePrinted",
            "InOutSalesRepresentative",
            "InOutNumberOfPackages",
            "InOutPickDate",
            "InOutShipDate",
            "InOutTrackingNumber",
            "InOutDateReceived",
            "InOutIsInTransit",
            "InOutIsApproved",
            "InOutIsInDispute",
            "InOutVolume",
            "InOutWeight",
            "InOutRmaNumber",
            "InOutReversalNumber",
            "InOutIsDropShip",
            "InOutDropShipBusinessPartnerId",
            "InOutVersion",
            "InOutCreatedBy",
            "InOutCreatedAt",
            "InOutUpdatedBy",
            "InOutUpdatedAt",
            "InOutActive",
            "InOutDeleted",
            "InOutLineId.InOutDocumentNumber",
            "InOutLineId.SkuIdProductId",
            "InOutLineId.SkuIdAttributeSetInstanceId",
    };

    public final static String[] propertyTypes = new String[] {
            "Long",
            "String",
            "String",
            "String",
            "String",
            "BigDecimal",
            "BigDecimal",
            "BigDecimal",
            "BigDecimal",
            "BigDecimal",
            "Boolean",
            "String",
            "Boolean",
            "Boolean",
            "BigDecimal",
            "Long",
            "Long",
            "Long",
            "String",
            "Date",
            "String",
            "Date",
            "Boolean",
            "Boolean",
            "Boolean",
            "String",
            "Boolean",
            "Boolean",
            "Boolean",
            "Integer",
            "String",
            "String",
            "Date",
            "Boolean",
            "String",
            "Date",
            "String",
            "String",
            "String",
            "Money",
            "String",
            "Money",
            "Date",
            "String",
            "Integer",
            "Date",
            "Date",
            "String",
            "Date",
            "Boolean",
            "Boolean",
            "Boolean",
            "BigDecimal",
            "BigDecimal",
            "String",
            "String",
            "Boolean",
            "String",
            "Long",
            "String",
            "Date",
            "String",
            "Date",
            "Boolean",
            "Boolean",
            "String",
            "String",
            "String",
    };

    public final static Map<String, String> propertyMap;

    static {
        propertyMap = new HashMap<String, String>();
        for (int i = 0; i < propertyNames.length; i++ ) {
            propertyMap.put(propertyNames[i], propertyTypes[i]);
        }
    }

}

